/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "asn/s1ap_v12.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER -D include/`
 */

#ifndef	_Cdma2000HORequiredIndication_H_
#define	_Cdma2000HORequiredIndication_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Cdma2000HORequiredIndication {
	Cdma2000HORequiredIndication_true	= 0
	/*
	 * Enumeration is extensible
	 */
} e_Cdma2000HORequiredIndication;

/* Cdma2000HORequiredIndication */
typedef long	 Cdma2000HORequiredIndication_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Cdma2000HORequiredIndication_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Cdma2000HORequiredIndication;
extern const asn_INTEGER_specifics_t asn_SPC_Cdma2000HORequiredIndication_specs_1;
asn_struct_free_f Cdma2000HORequiredIndication_free;
asn_struct_print_f Cdma2000HORequiredIndication_print;
asn_constr_check_f Cdma2000HORequiredIndication_constraint;
per_type_decoder_f Cdma2000HORequiredIndication_decode_aper;
per_type_encoder_f Cdma2000HORequiredIndication_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _Cdma2000HORequiredIndication_H_ */
#include <asn_internal.h>
