/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "asn/s1ap_v12.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER -D include/`
 */

#ifndef	_Cdma2000OneXRAND_H_
#define	_Cdma2000OneXRAND_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Cdma2000OneXRAND */
typedef OCTET_STRING_t	 Cdma2000OneXRAND_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Cdma2000OneXRAND;
asn_struct_free_f Cdma2000OneXRAND_free;
asn_struct_print_f Cdma2000OneXRAND_print;
asn_constr_check_f Cdma2000OneXRAND_constraint;
per_type_decoder_f Cdma2000OneXRAND_decode_aper;
per_type_encoder_f Cdma2000OneXRAND_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _Cdma2000OneXRAND_H_ */
#include <asn_internal.h>
