/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "asn/s1ap_v12.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER -D include/`
 */

#ifndef	_Correlation_ID_H_
#define	_Correlation_ID_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Correlation-ID */
typedef OCTET_STRING_t	 Correlation_ID_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Correlation_ID_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Correlation_ID;
asn_struct_free_f Correlation_ID_free;
asn_struct_print_f Correlation_ID_print;
asn_constr_check_f Correlation_ID_constraint;
per_type_decoder_f Correlation_ID_decode_aper;
per_type_encoder_f Correlation_ID_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _Correlation_ID_H_ */
#include <asn_internal.h>
