/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-PDU-Contents"
 * 	found in "asn/s1ap_v12.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER -D include/`
 */

#ifndef	_E_RABAdmittedList_H_
#define	_E_RABAdmittedList_H_


#include <asn_application.h>

/* Including external dependencies */
#include "E-RAB-IE-ContainerList.h"

#ifdef __cplusplus
extern "C" {
#endif

/* E-RABAdmittedList */
typedef E_RAB_IE_ContainerList_973P2_t	 E_RABAdmittedList_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_E_RABAdmittedList_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_E_RABAdmittedList;
asn_struct_free_f E_RABAdmittedList_free;
asn_struct_print_f E_RABAdmittedList_print;
asn_constr_check_f E_RABAdmittedList_constraint;
per_type_decoder_f E_RABAdmittedList_decode_aper;
per_type_encoder_f E_RABAdmittedList_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _E_RABAdmittedList_H_ */
#include <asn_internal.h>
