/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-PDU-Contents"
 * 	found in "asn/s1ap_v12.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER -D include/`
 */

#include "E-RAB-IE-ContainerList.h"

int
E_RAB_IE_ContainerList_973P0_constraint(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1UL && size <= 256UL)) {
		/* Perform validation of the inner elements */
		return SEQUENCE_OF_constraint(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

/*
 * This type is implemented using ProtocolIE_ContainerList_5575P0,
 * so here we adjust the DEF accordingly.
 */
int
E_RAB_IE_ContainerList_973P1_constraint(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1UL && size <= 256UL)) {
		/* Perform validation of the inner elements */
		return SEQUENCE_OF_constraint(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

/*
 * This type is implemented using ProtocolIE_ContainerList_5575P1,
 * so here we adjust the DEF accordingly.
 */
int
E_RAB_IE_ContainerList_973P2_constraint(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1UL && size <= 256UL)) {
		/* Perform validation of the inner elements */
		return SEQUENCE_OF_constraint(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

/*
 * This type is implemented using ProtocolIE_ContainerList_5575P2,
 * so here we adjust the DEF accordingly.
 */
int
E_RAB_IE_ContainerList_973P3_constraint(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1UL && size <= 256UL)) {
		/* Perform validation of the inner elements */
		return SEQUENCE_OF_constraint(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

/*
 * This type is implemented using ProtocolIE_ContainerList_5575P3,
 * so here we adjust the DEF accordingly.
 */
int
E_RAB_IE_ContainerList_973P4_constraint(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1UL && size <= 256UL)) {
		/* Perform validation of the inner elements */
		return SEQUENCE_OF_constraint(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

/*
 * This type is implemented using ProtocolIE_ContainerList_5575P4,
 * so here we adjust the DEF accordingly.
 */
int
E_RAB_IE_ContainerList_973P5_constraint(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1UL && size <= 256UL)) {
		/* Perform validation of the inner elements */
		return SEQUENCE_OF_constraint(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

/*
 * This type is implemented using ProtocolIE_ContainerList_5575P5,
 * so here we adjust the DEF accordingly.
 */
int
E_RAB_IE_ContainerList_973P6_constraint(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1UL && size <= 256UL)) {
		/* Perform validation of the inner elements */
		return SEQUENCE_OF_constraint(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

/*
 * This type is implemented using ProtocolIE_ContainerList_5575P6,
 * so here we adjust the DEF accordingly.
 */
int
E_RAB_IE_ContainerList_973P7_constraint(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1UL && size <= 256UL)) {
		/* Perform validation of the inner elements */
		return SEQUENCE_OF_constraint(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

/*
 * This type is implemented using ProtocolIE_ContainerList_5575P7,
 * so here we adjust the DEF accordingly.
 */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_E_RAB_IE_ContainerList_973P0_constr_1 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 8,  8,  1,  256 }	/* (SIZE(1..256)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_E_RAB_IE_ContainerList_973P1_constr_2 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 8,  8,  1,  256 }	/* (SIZE(1..256)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_E_RAB_IE_ContainerList_973P2_constr_3 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 8,  8,  1,  256 }	/* (SIZE(1..256)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_E_RAB_IE_ContainerList_973P3_constr_4 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 8,  8,  1,  256 }	/* (SIZE(1..256)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_E_RAB_IE_ContainerList_973P4_constr_5 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 8,  8,  1,  256 }	/* (SIZE(1..256)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_E_RAB_IE_ContainerList_973P5_constr_6 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 8,  8,  1,  256 }	/* (SIZE(1..256)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_E_RAB_IE_ContainerList_973P6_constr_7 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 8,  8,  1,  256 }	/* (SIZE(1..256)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_E_RAB_IE_ContainerList_973P7_constr_8 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 8,  8,  1,  256 }	/* (SIZE(1..256)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
static const ber_tlv_tag_t asn_DEF_E_RAB_IE_ContainerList_973P0_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_E_RAB_IE_ContainerList_973P0 = {
	"E-RAB-IE-ContainerList",
	"E-RAB-IE-ContainerList",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_E_RAB_IE_ContainerList_973P0_tags_1,
	sizeof(asn_DEF_E_RAB_IE_ContainerList_973P0_tags_1)
		/sizeof(asn_DEF_E_RAB_IE_ContainerList_973P0_tags_1[0]), /* 1 */
	asn_DEF_E_RAB_IE_ContainerList_973P0_tags_1,	/* Same as above */
	sizeof(asn_DEF_E_RAB_IE_ContainerList_973P0_tags_1)
		/sizeof(asn_DEF_E_RAB_IE_ContainerList_973P0_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_E_RAB_IE_ContainerList_973P0_constr_1,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		E_RAB_IE_ContainerList_973P0_constraint
	},
	asn_MBR_ProtocolIE_ContainerList_5575P0_1,
	1,	/* Single element */
	&asn_SPC_ProtocolIE_ContainerList_5575P0_specs_1	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_E_RAB_IE_ContainerList_973P1_tags_2[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_E_RAB_IE_ContainerList_973P1 = {
	"E-RAB-IE-ContainerList",
	"E-RAB-IE-ContainerList",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_E_RAB_IE_ContainerList_973P1_tags_2,
	sizeof(asn_DEF_E_RAB_IE_ContainerList_973P1_tags_2)
		/sizeof(asn_DEF_E_RAB_IE_ContainerList_973P1_tags_2[0]), /* 1 */
	asn_DEF_E_RAB_IE_ContainerList_973P1_tags_2,	/* Same as above */
	sizeof(asn_DEF_E_RAB_IE_ContainerList_973P1_tags_2)
		/sizeof(asn_DEF_E_RAB_IE_ContainerList_973P1_tags_2[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_E_RAB_IE_ContainerList_973P1_constr_2,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		E_RAB_IE_ContainerList_973P1_constraint
	},
	asn_MBR_ProtocolIE_ContainerList_5575P1_3,
	1,	/* Single element */
	&asn_SPC_ProtocolIE_ContainerList_5575P1_specs_3	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_E_RAB_IE_ContainerList_973P2_tags_3[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_E_RAB_IE_ContainerList_973P2 = {
	"E-RAB-IE-ContainerList",
	"E-RAB-IE-ContainerList",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_E_RAB_IE_ContainerList_973P2_tags_3,
	sizeof(asn_DEF_E_RAB_IE_ContainerList_973P2_tags_3)
		/sizeof(asn_DEF_E_RAB_IE_ContainerList_973P2_tags_3[0]), /* 1 */
	asn_DEF_E_RAB_IE_ContainerList_973P2_tags_3,	/* Same as above */
	sizeof(asn_DEF_E_RAB_IE_ContainerList_973P2_tags_3)
		/sizeof(asn_DEF_E_RAB_IE_ContainerList_973P2_tags_3[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_E_RAB_IE_ContainerList_973P2_constr_3,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		E_RAB_IE_ContainerList_973P2_constraint
	},
	asn_MBR_ProtocolIE_ContainerList_5575P2_5,
	1,	/* Single element */
	&asn_SPC_ProtocolIE_ContainerList_5575P2_specs_5	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_E_RAB_IE_ContainerList_973P3_tags_4[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_E_RAB_IE_ContainerList_973P3 = {
	"E-RAB-IE-ContainerList",
	"E-RAB-IE-ContainerList",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_E_RAB_IE_ContainerList_973P3_tags_4,
	sizeof(asn_DEF_E_RAB_IE_ContainerList_973P3_tags_4)
		/sizeof(asn_DEF_E_RAB_IE_ContainerList_973P3_tags_4[0]), /* 1 */
	asn_DEF_E_RAB_IE_ContainerList_973P3_tags_4,	/* Same as above */
	sizeof(asn_DEF_E_RAB_IE_ContainerList_973P3_tags_4)
		/sizeof(asn_DEF_E_RAB_IE_ContainerList_973P3_tags_4[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_E_RAB_IE_ContainerList_973P3_constr_4,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		E_RAB_IE_ContainerList_973P3_constraint
	},
	asn_MBR_ProtocolIE_ContainerList_5575P3_7,
	1,	/* Single element */
	&asn_SPC_ProtocolIE_ContainerList_5575P3_specs_7	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_E_RAB_IE_ContainerList_973P4_tags_5[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_E_RAB_IE_ContainerList_973P4 = {
	"E-RAB-IE-ContainerList",
	"E-RAB-IE-ContainerList",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_E_RAB_IE_ContainerList_973P4_tags_5,
	sizeof(asn_DEF_E_RAB_IE_ContainerList_973P4_tags_5)
		/sizeof(asn_DEF_E_RAB_IE_ContainerList_973P4_tags_5[0]), /* 1 */
	asn_DEF_E_RAB_IE_ContainerList_973P4_tags_5,	/* Same as above */
	sizeof(asn_DEF_E_RAB_IE_ContainerList_973P4_tags_5)
		/sizeof(asn_DEF_E_RAB_IE_ContainerList_973P4_tags_5[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_E_RAB_IE_ContainerList_973P4_constr_5,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		E_RAB_IE_ContainerList_973P4_constraint
	},
	asn_MBR_ProtocolIE_ContainerList_5575P4_9,
	1,	/* Single element */
	&asn_SPC_ProtocolIE_ContainerList_5575P4_specs_9	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_E_RAB_IE_ContainerList_973P5_tags_6[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_E_RAB_IE_ContainerList_973P5 = {
	"E-RAB-IE-ContainerList",
	"E-RAB-IE-ContainerList",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_E_RAB_IE_ContainerList_973P5_tags_6,
	sizeof(asn_DEF_E_RAB_IE_ContainerList_973P5_tags_6)
		/sizeof(asn_DEF_E_RAB_IE_ContainerList_973P5_tags_6[0]), /* 1 */
	asn_DEF_E_RAB_IE_ContainerList_973P5_tags_6,	/* Same as above */
	sizeof(asn_DEF_E_RAB_IE_ContainerList_973P5_tags_6)
		/sizeof(asn_DEF_E_RAB_IE_ContainerList_973P5_tags_6[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_E_RAB_IE_ContainerList_973P5_constr_6,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		E_RAB_IE_ContainerList_973P5_constraint
	},
	asn_MBR_ProtocolIE_ContainerList_5575P5_11,
	1,	/* Single element */
	&asn_SPC_ProtocolIE_ContainerList_5575P5_specs_11	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_E_RAB_IE_ContainerList_973P6_tags_7[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_E_RAB_IE_ContainerList_973P6 = {
	"E-RAB-IE-ContainerList",
	"E-RAB-IE-ContainerList",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_E_RAB_IE_ContainerList_973P6_tags_7,
	sizeof(asn_DEF_E_RAB_IE_ContainerList_973P6_tags_7)
		/sizeof(asn_DEF_E_RAB_IE_ContainerList_973P6_tags_7[0]), /* 1 */
	asn_DEF_E_RAB_IE_ContainerList_973P6_tags_7,	/* Same as above */
	sizeof(asn_DEF_E_RAB_IE_ContainerList_973P6_tags_7)
		/sizeof(asn_DEF_E_RAB_IE_ContainerList_973P6_tags_7[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_E_RAB_IE_ContainerList_973P6_constr_7,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		E_RAB_IE_ContainerList_973P6_constraint
	},
	asn_MBR_ProtocolIE_ContainerList_5575P6_13,
	1,	/* Single element */
	&asn_SPC_ProtocolIE_ContainerList_5575P6_specs_13	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_E_RAB_IE_ContainerList_973P7_tags_8[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_E_RAB_IE_ContainerList_973P7 = {
	"E-RAB-IE-ContainerList",
	"E-RAB-IE-ContainerList",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_E_RAB_IE_ContainerList_973P7_tags_8,
	sizeof(asn_DEF_E_RAB_IE_ContainerList_973P7_tags_8)
		/sizeof(asn_DEF_E_RAB_IE_ContainerList_973P7_tags_8[0]), /* 1 */
	asn_DEF_E_RAB_IE_ContainerList_973P7_tags_8,	/* Same as above */
	sizeof(asn_DEF_E_RAB_IE_ContainerList_973P7_tags_8)
		/sizeof(asn_DEF_E_RAB_IE_ContainerList_973P7_tags_8[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_E_RAB_IE_ContainerList_973P7_constr_8,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		E_RAB_IE_ContainerList_973P7_constraint
	},
	asn_MBR_ProtocolIE_ContainerList_5575P7_15,
	1,	/* Single element */
	&asn_SPC_ProtocolIE_ContainerList_5575P7_specs_15	/* Additional specs */
};

