/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "asn/s1ap_v12.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER -D include/`
 */

#ifndef	_KillAllWarningMessages_H_
#define	_KillAllWarningMessages_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum KillAllWarningMessages {
	KillAllWarningMessages_true	= 0
} e_KillAllWarningMessages;

/* KillAllWarningMessages */
typedef long	 KillAllWarningMessages_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_KillAllWarningMessages_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_KillAllWarningMessages;
extern const asn_INTEGER_specifics_t asn_SPC_KillAllWarningMessages_specs_1;
asn_struct_free_f KillAllWarningMessages_free;
asn_struct_print_f KillAllWarningMessages_print;
asn_constr_check_f KillAllWarningMessages_constraint;
per_type_decoder_f KillAllWarningMessages_decode_aper;
per_type_encoder_f KillAllWarningMessages_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _KillAllWarningMessages_H_ */
#include <asn_internal.h>
