/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "asn/s1ap_v12.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER -D include/`
 */

#ifndef	_M_TMSI_H_
#define	_M_TMSI_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* M-TMSI */
typedef OCTET_STRING_t	 M_TMSI_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_M_TMSI_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_M_TMSI;
asn_struct_free_f M_TMSI_free;
asn_struct_print_f M_TMSI_print;
asn_constr_check_f M_TMSI_constraint;
per_type_decoder_f M_TMSI_decode_aper;
per_type_encoder_f M_TMSI_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _M_TMSI_H_ */
#include <asn_internal.h>
