/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "asn/s1ap_v12.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER -D include/`
 */

#ifndef	_PDCP_SNExtended_H_
#define	_PDCP_SNExtended_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* PDCP-SNExtended */
typedef long	 PDCP_SNExtended_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_PDCP_SNExtended_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_PDCP_SNExtended;
asn_struct_free_f PDCP_SNExtended_free;
asn_struct_print_f PDCP_SNExtended_print;
asn_constr_check_f PDCP_SNExtended_constraint;
per_type_decoder_f PDCP_SNExtended_decode_aper;
per_type_encoder_f PDCP_SNExtended_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _PDCP_SNExtended_H_ */
#include <asn_internal.h>
