/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 */

struct asn_TYPE_descriptor_s;	/* Forward declaration */

extern struct asn_TYPE_descriptor_s asn_DEF_S1AP_PDU;
extern struct asn_TYPE_descriptor_s asn_DEF_InitiatingMessage;
extern struct asn_TYPE_descriptor_s asn_DEF_SuccessfulOutcome;
extern struct asn_TYPE_descriptor_s asn_DEF_UnsuccessfulOutcome;
extern struct asn_TYPE_descriptor_s asn_DEF_HandoverRequired;
extern struct asn_TYPE_descriptor_s asn_DEF_HandoverCommand;
extern struct asn_TYPE_descriptor_s asn_DEF_E_RABSubjecttoDataForwardingList;
extern struct asn_TYPE_descriptor_s asn_DEF_E_RABDataForwardingItem;
extern struct asn_TYPE_descriptor_s asn_DEF_HandoverPreparationFailure;
extern struct asn_TYPE_descriptor_s asn_DEF_HandoverRequest;
extern struct asn_TYPE_descriptor_s asn_DEF_E_RABToBeSetupListHOReq;
extern struct asn_TYPE_descriptor_s asn_DEF_E_RABToBeSetupItemHOReq;
extern struct asn_TYPE_descriptor_s asn_DEF_HandoverRequestAcknowledge;
extern struct asn_TYPE_descriptor_s asn_DEF_E_RABAdmittedList;
extern struct asn_TYPE_descriptor_s asn_DEF_E_RABAdmittedItem;
extern struct asn_TYPE_descriptor_s asn_DEF_E_RABFailedtoSetupListHOReqAck;
extern struct asn_TYPE_descriptor_s asn_DEF_E_RABFailedToSetupItemHOReqAck;
extern struct asn_TYPE_descriptor_s asn_DEF_HandoverFailure;
extern struct asn_TYPE_descriptor_s asn_DEF_HandoverNotify;
extern struct asn_TYPE_descriptor_s asn_DEF_PathSwitchRequest;
extern struct asn_TYPE_descriptor_s asn_DEF_E_RABToBeSwitchedDLList;
extern struct asn_TYPE_descriptor_s asn_DEF_E_RABToBeSwitchedDLItem;
extern struct asn_TYPE_descriptor_s asn_DEF_PathSwitchRequestAcknowledge;
extern struct asn_TYPE_descriptor_s asn_DEF_E_RABToBeSwitchedULList;
extern struct asn_TYPE_descriptor_s asn_DEF_E_RABToBeSwitchedULItem;
extern struct asn_TYPE_descriptor_s asn_DEF_PathSwitchRequestFailure;
extern struct asn_TYPE_descriptor_s asn_DEF_HandoverCancel;
extern struct asn_TYPE_descriptor_s asn_DEF_HandoverCancelAcknowledge;
extern struct asn_TYPE_descriptor_s asn_DEF_E_RABSetupRequest;
extern struct asn_TYPE_descriptor_s asn_DEF_E_RABToBeSetupListBearerSUReq;
extern struct asn_TYPE_descriptor_s asn_DEF_E_RABToBeSetupItemBearerSUReq;
extern struct asn_TYPE_descriptor_s asn_DEF_E_RABSetupResponse;
extern struct asn_TYPE_descriptor_s asn_DEF_E_RABSetupListBearerSURes;
extern struct asn_TYPE_descriptor_s asn_DEF_E_RABSetupItemBearerSURes;
extern struct asn_TYPE_descriptor_s asn_DEF_E_RABModifyRequest;
extern struct asn_TYPE_descriptor_s asn_DEF_E_RABToBeModifiedListBearerModReq;
extern struct asn_TYPE_descriptor_s asn_DEF_E_RABToBeModifiedItemBearerModReq;
extern struct asn_TYPE_descriptor_s asn_DEF_E_RABModifyResponse;
extern struct asn_TYPE_descriptor_s asn_DEF_E_RABModifyListBearerModRes;
extern struct asn_TYPE_descriptor_s asn_DEF_E_RABModifyItemBearerModRes;
extern struct asn_TYPE_descriptor_s asn_DEF_E_RABReleaseCommand;
extern struct asn_TYPE_descriptor_s asn_DEF_E_RABReleaseResponse;
extern struct asn_TYPE_descriptor_s asn_DEF_E_RABReleaseListBearerRelComp;
extern struct asn_TYPE_descriptor_s asn_DEF_E_RABReleaseItemBearerRelComp;
extern struct asn_TYPE_descriptor_s asn_DEF_E_RABReleaseIndication;
extern struct asn_TYPE_descriptor_s asn_DEF_InitialContextSetupRequest;
extern struct asn_TYPE_descriptor_s asn_DEF_E_RABToBeSetupListCtxtSUReq;
extern struct asn_TYPE_descriptor_s asn_DEF_E_RABToBeSetupItemCtxtSUReq;
extern struct asn_TYPE_descriptor_s asn_DEF_InitialContextSetupResponse;
extern struct asn_TYPE_descriptor_s asn_DEF_E_RABSetupListCtxtSURes;
extern struct asn_TYPE_descriptor_s asn_DEF_E_RABSetupItemCtxtSURes;
extern struct asn_TYPE_descriptor_s asn_DEF_InitialContextSetupFailure;
extern struct asn_TYPE_descriptor_s asn_DEF_Paging;
extern struct asn_TYPE_descriptor_s asn_DEF_TAIList;
extern struct asn_TYPE_descriptor_s asn_DEF_TAIItem;
extern struct asn_TYPE_descriptor_s asn_DEF_UEContextReleaseRequest;
extern struct asn_TYPE_descriptor_s asn_DEF_UEContextReleaseCommand;
extern struct asn_TYPE_descriptor_s asn_DEF_UEContextReleaseComplete;
extern struct asn_TYPE_descriptor_s asn_DEF_UEContextModificationRequest;
extern struct asn_TYPE_descriptor_s asn_DEF_UEContextModificationResponse;
extern struct asn_TYPE_descriptor_s asn_DEF_UEContextModificationFailure;
extern struct asn_TYPE_descriptor_s asn_DEF_UERadioCapabilityMatchRequest;
extern struct asn_TYPE_descriptor_s asn_DEF_UERadioCapabilityMatchResponse;
extern struct asn_TYPE_descriptor_s asn_DEF_DownlinkNASTransport;
extern struct asn_TYPE_descriptor_s asn_DEF_InitialUEMessage;
extern struct asn_TYPE_descriptor_s asn_DEF_UplinkNASTransport;
extern struct asn_TYPE_descriptor_s asn_DEF_NASNonDeliveryIndication;
extern struct asn_TYPE_descriptor_s asn_DEF_Reset;
extern struct asn_TYPE_descriptor_s asn_DEF_ResetType;
extern struct asn_TYPE_descriptor_s asn_DEF_ResetAll;
extern struct asn_TYPE_descriptor_s asn_DEF_UE_associatedLogicalS1_ConnectionListRes;
extern struct asn_TYPE_descriptor_s asn_DEF_ResetAcknowledge;
extern struct asn_TYPE_descriptor_s asn_DEF_UE_associatedLogicalS1_ConnectionListResAck;
extern struct asn_TYPE_descriptor_s asn_DEF_ErrorIndication;
extern struct asn_TYPE_descriptor_s asn_DEF_S1SetupRequest;
extern struct asn_TYPE_descriptor_s asn_DEF_S1SetupResponse;
extern struct asn_TYPE_descriptor_s asn_DEF_S1SetupFailure;
extern struct asn_TYPE_descriptor_s asn_DEF_ENBConfigurationUpdate;
extern struct asn_TYPE_descriptor_s asn_DEF_ENBConfigurationUpdateAcknowledge;
extern struct asn_TYPE_descriptor_s asn_DEF_ENBConfigurationUpdateFailure;
extern struct asn_TYPE_descriptor_s asn_DEF_MMEConfigurationUpdate;
extern struct asn_TYPE_descriptor_s asn_DEF_MMEConfigurationUpdateAcknowledge;
extern struct asn_TYPE_descriptor_s asn_DEF_MMEConfigurationUpdateFailure;
extern struct asn_TYPE_descriptor_s asn_DEF_DownlinkS1cdma2000tunnelling;
extern struct asn_TYPE_descriptor_s asn_DEF_UplinkS1cdma2000tunnelling;
extern struct asn_TYPE_descriptor_s asn_DEF_UECapabilityInfoIndication;
extern struct asn_TYPE_descriptor_s asn_DEF_ENBStatusTransfer;
extern struct asn_TYPE_descriptor_s asn_DEF_MMEStatusTransfer;
extern struct asn_TYPE_descriptor_s asn_DEF_TraceStart;
extern struct asn_TYPE_descriptor_s asn_DEF_TraceFailureIndication;
extern struct asn_TYPE_descriptor_s asn_DEF_DeactivateTrace;
extern struct asn_TYPE_descriptor_s asn_DEF_CellTrafficTrace;
extern struct asn_TYPE_descriptor_s asn_DEF_LocationReportingControl;
extern struct asn_TYPE_descriptor_s asn_DEF_LocationReportingFailureIndication;
extern struct asn_TYPE_descriptor_s asn_DEF_LocationReport;
extern struct asn_TYPE_descriptor_s asn_DEF_OverloadStart;
extern struct asn_TYPE_descriptor_s asn_DEF_OverloadStop;
extern struct asn_TYPE_descriptor_s asn_DEF_WriteReplaceWarningRequest;
extern struct asn_TYPE_descriptor_s asn_DEF_WriteReplaceWarningResponse;
extern struct asn_TYPE_descriptor_s asn_DEF_ENBDirectInformationTransfer;
extern struct asn_TYPE_descriptor_s asn_DEF_Inter_SystemInformationTransferType;
extern struct asn_TYPE_descriptor_s asn_DEF_MMEDirectInformationTransfer;
extern struct asn_TYPE_descriptor_s asn_DEF_ENBConfigurationTransfer;
extern struct asn_TYPE_descriptor_s asn_DEF_MMEConfigurationTransfer;
extern struct asn_TYPE_descriptor_s asn_DEF_PrivateMessage;
extern struct asn_TYPE_descriptor_s asn_DEF_KillRequest;
extern struct asn_TYPE_descriptor_s asn_DEF_KillResponse;
extern struct asn_TYPE_descriptor_s asn_DEF_PWSRestartIndication;
extern struct asn_TYPE_descriptor_s asn_DEF_DownlinkUEAssociatedLPPaTransport;
extern struct asn_TYPE_descriptor_s asn_DEF_UplinkUEAssociatedLPPaTransport;
extern struct asn_TYPE_descriptor_s asn_DEF_DownlinkNonUEAssociatedLPPaTransport;
extern struct asn_TYPE_descriptor_s asn_DEF_UplinkNonUEAssociatedLPPaTransport;
extern struct asn_TYPE_descriptor_s asn_DEF_E_RABModificationIndication;
extern struct asn_TYPE_descriptor_s asn_DEF_E_RABToBeModifiedListBearerModInd;
extern struct asn_TYPE_descriptor_s asn_DEF_E_RABToBeModifiedItemBearerModInd;
extern struct asn_TYPE_descriptor_s asn_DEF_E_RABNotToBeModifiedListBearerModInd;
extern struct asn_TYPE_descriptor_s asn_DEF_E_RABNotToBeModifiedItemBearerModInd;
extern struct asn_TYPE_descriptor_s asn_DEF_E_RABModificationConfirm;
extern struct asn_TYPE_descriptor_s asn_DEF_E_RABModifyListBearerModConf;
extern struct asn_TYPE_descriptor_s asn_DEF_E_RABModifyItemBearerModConf;
extern struct asn_TYPE_descriptor_s asn_DEF_AreaScopeOfMDT;
extern struct asn_TYPE_descriptor_s asn_DEF_AllocationAndRetentionPriority;
extern struct asn_TYPE_descriptor_s asn_DEF_Bearers_SubjectToStatusTransferList;
extern struct asn_TYPE_descriptor_s asn_DEF_Bearers_SubjectToStatusTransfer_Item;
extern struct asn_TYPE_descriptor_s asn_DEF_BitRate;
extern struct asn_TYPE_descriptor_s asn_DEF_BPLMNs;
extern struct asn_TYPE_descriptor_s asn_DEF_BroadcastCancelledAreaList;
extern struct asn_TYPE_descriptor_s asn_DEF_BroadcastCompletedAreaList;
extern struct asn_TYPE_descriptor_s asn_DEF_CancelledCellinEAI;
extern struct asn_TYPE_descriptor_s asn_DEF_CancelledCellinEAI_Item;
extern struct asn_TYPE_descriptor_s asn_DEF_CancelledCellinTAI;
extern struct asn_TYPE_descriptor_s asn_DEF_CancelledCellinTAI_Item;
extern struct asn_TYPE_descriptor_s asn_DEF_Cause;
extern struct asn_TYPE_descriptor_s asn_DEF_CauseMisc;
extern struct asn_TYPE_descriptor_s asn_DEF_CauseProtocol;
extern struct asn_TYPE_descriptor_s asn_DEF_CauseRadioNetwork;
extern struct asn_TYPE_descriptor_s asn_DEF_CauseTransport;
extern struct asn_TYPE_descriptor_s asn_DEF_CauseNas;
extern struct asn_TYPE_descriptor_s asn_DEF_CellAccessMode;
extern struct asn_TYPE_descriptor_s asn_DEF_CellIdentity;
extern struct asn_TYPE_descriptor_s asn_DEF_CellID_Broadcast;
extern struct asn_TYPE_descriptor_s asn_DEF_CellID_Broadcast_Item;
extern struct asn_TYPE_descriptor_s asn_DEF_CellID_Cancelled;
extern struct asn_TYPE_descriptor_s asn_DEF_CellID_Cancelled_Item;
extern struct asn_TYPE_descriptor_s asn_DEF_CellBasedMDT;
extern struct asn_TYPE_descriptor_s asn_DEF_CellIdListforMDT;
extern struct asn_TYPE_descriptor_s asn_DEF_Cdma2000PDU;
extern struct asn_TYPE_descriptor_s asn_DEF_Cdma2000RATType;
extern struct asn_TYPE_descriptor_s asn_DEF_Cdma2000SectorID;
extern struct asn_TYPE_descriptor_s asn_DEF_Cdma2000HOStatus;
extern struct asn_TYPE_descriptor_s asn_DEF_Cdma2000HORequiredIndication;
extern struct asn_TYPE_descriptor_s asn_DEF_Cdma2000OneXSRVCCInfo;
extern struct asn_TYPE_descriptor_s asn_DEF_Cdma2000OneXMEID;
extern struct asn_TYPE_descriptor_s asn_DEF_Cdma2000OneXMSI;
extern struct asn_TYPE_descriptor_s asn_DEF_Cdma2000OneXPilot;
extern struct asn_TYPE_descriptor_s asn_DEF_Cdma2000OneXRAND;
extern struct asn_TYPE_descriptor_s asn_DEF_Cell_Size;
extern struct asn_TYPE_descriptor_s asn_DEF_CellType;
extern struct asn_TYPE_descriptor_s asn_DEF_CGI;
extern struct asn_TYPE_descriptor_s asn_DEF_CI;
extern struct asn_TYPE_descriptor_s asn_DEF_CNDomain;
extern struct asn_TYPE_descriptor_s asn_DEF_ConcurrentWarningMessageIndicator;
extern struct asn_TYPE_descriptor_s asn_DEF_Correlation_ID;
extern struct asn_TYPE_descriptor_s asn_DEF_CSFallbackIndicator;
extern struct asn_TYPE_descriptor_s asn_DEF_AdditionalCSFallbackIndicator;
extern struct asn_TYPE_descriptor_s asn_DEF_CSG_Id;
extern struct asn_TYPE_descriptor_s asn_DEF_CSG_IdList;
extern struct asn_TYPE_descriptor_s asn_DEF_CSG_IdList_Item;
extern struct asn_TYPE_descriptor_s asn_DEF_CSGMembershipStatus;
extern struct asn_TYPE_descriptor_s asn_DEF_COUNTvalue;
extern struct asn_TYPE_descriptor_s asn_DEF_COUNTValueExtended;
extern struct asn_TYPE_descriptor_s asn_DEF_CriticalityDiagnostics;
extern struct asn_TYPE_descriptor_s asn_DEF_CriticalityDiagnostics_IE_List;
extern struct asn_TYPE_descriptor_s asn_DEF_CriticalityDiagnostics_IE_Item;
extern struct asn_TYPE_descriptor_s asn_DEF_DataCodingScheme;
extern struct asn_TYPE_descriptor_s asn_DEF_DL_Forwarding;
extern struct asn_TYPE_descriptor_s asn_DEF_Direct_Forwarding_Path_Availability;
extern struct asn_TYPE_descriptor_s asn_DEF_Data_Forwarding_Not_Possible;
extern struct asn_TYPE_descriptor_s asn_DEF_EARFCN;
extern struct asn_TYPE_descriptor_s asn_DEF_ECGIList;
extern struct asn_TYPE_descriptor_s asn_DEF_EmergencyAreaIDList;
extern struct asn_TYPE_descriptor_s asn_DEF_EmergencyAreaID;
extern struct asn_TYPE_descriptor_s asn_DEF_EmergencyAreaID_Broadcast;
extern struct asn_TYPE_descriptor_s asn_DEF_EmergencyAreaID_Broadcast_Item;
extern struct asn_TYPE_descriptor_s asn_DEF_EmergencyAreaID_Cancelled;
extern struct asn_TYPE_descriptor_s asn_DEF_EmergencyAreaID_Cancelled_Item;
extern struct asn_TYPE_descriptor_s asn_DEF_CompletedCellinEAI;
extern struct asn_TYPE_descriptor_s asn_DEF_CompletedCellinEAI_Item;
extern struct asn_TYPE_descriptor_s asn_DEF_ECGI_List;
extern struct asn_TYPE_descriptor_s asn_DEF_EmergencyAreaIDListForRestart;
extern struct asn_TYPE_descriptor_s asn_DEF_ENB_ID;
extern struct asn_TYPE_descriptor_s asn_DEF_GERAN_Cell_ID;
extern struct asn_TYPE_descriptor_s asn_DEF_Global_ENB_ID;
extern struct asn_TYPE_descriptor_s asn_DEF_GUMMEIList;
extern struct asn_TYPE_descriptor_s asn_DEF_ENB_StatusTransfer_TransparentContainer;
extern struct asn_TYPE_descriptor_s asn_DEF_ENB_UE_S1AP_ID;
extern struct asn_TYPE_descriptor_s asn_DEF_ENBname;
extern struct asn_TYPE_descriptor_s asn_DEF_ENBX2TLAs;
extern struct asn_TYPE_descriptor_s asn_DEF_EncryptionAlgorithms;
extern struct asn_TYPE_descriptor_s asn_DEF_EPLMNs;
extern struct asn_TYPE_descriptor_s asn_DEF_EventType;
extern struct asn_TYPE_descriptor_s asn_DEF_E_RAB_ID;
extern struct asn_TYPE_descriptor_s asn_DEF_E_RABInformationList;
extern struct asn_TYPE_descriptor_s asn_DEF_E_RABInformationListItem;
extern struct asn_TYPE_descriptor_s asn_DEF_E_RABList;
extern struct asn_TYPE_descriptor_s asn_DEF_E_RABItem;
extern struct asn_TYPE_descriptor_s asn_DEF_E_RABLevelQoSParameters;
extern struct asn_TYPE_descriptor_s asn_DEF_EUTRAN_CGI;
extern struct asn_TYPE_descriptor_s asn_DEF_EUTRANRoundTripDelayEstimationInfo;
extern struct asn_TYPE_descriptor_s asn_DEF_ExpectedUEBehaviour;
extern struct asn_TYPE_descriptor_s asn_DEF_ExpectedUEActivityBehaviour;
extern struct asn_TYPE_descriptor_s asn_DEF_ExpectedActivityPeriod;
extern struct asn_TYPE_descriptor_s asn_DEF_ExpectedIdlePeriod;
extern struct asn_TYPE_descriptor_s asn_DEF_SourceOfUEActivityBehaviourInformation;
extern struct asn_TYPE_descriptor_s asn_DEF_ExpectedHOInterval;
extern struct asn_TYPE_descriptor_s asn_DEF_ExtendedRNC_ID;
extern struct asn_TYPE_descriptor_s asn_DEF_ExtendedRepetitionPeriod;
extern struct asn_TYPE_descriptor_s asn_DEF_ForbiddenInterRATs;
extern struct asn_TYPE_descriptor_s asn_DEF_ForbiddenTAs;
extern struct asn_TYPE_descriptor_s asn_DEF_ForbiddenTAs_Item;
extern struct asn_TYPE_descriptor_s asn_DEF_ForbiddenTACs;
extern struct asn_TYPE_descriptor_s asn_DEF_ForbiddenLAs;
extern struct asn_TYPE_descriptor_s asn_DEF_ForbiddenLAs_Item;
extern struct asn_TYPE_descriptor_s asn_DEF_ForbiddenLACs;
extern struct asn_TYPE_descriptor_s asn_DEF_GBR_QosInformation;
extern struct asn_TYPE_descriptor_s asn_DEF_GTP_TEID;
extern struct asn_TYPE_descriptor_s asn_DEF_GUMMEI;
extern struct asn_TYPE_descriptor_s asn_DEF_GUMMEIType;
extern struct asn_TYPE_descriptor_s asn_DEF_GWContextReleaseIndication;
extern struct asn_TYPE_descriptor_s asn_DEF_HandoverRestrictionList;
extern struct asn_TYPE_descriptor_s asn_DEF_HandoverType;
extern struct asn_TYPE_descriptor_s asn_DEF_HFN;
extern struct asn_TYPE_descriptor_s asn_DEF_HFNModified;
extern struct asn_TYPE_descriptor_s asn_DEF_Masked_IMEISV;
extern struct asn_TYPE_descriptor_s asn_DEF_ImmediateMDT;
extern struct asn_TYPE_descriptor_s asn_DEF_IMSI;
extern struct asn_TYPE_descriptor_s asn_DEF_IntegrityProtectionAlgorithms;
extern struct asn_TYPE_descriptor_s asn_DEF_InterfacesToTrace;
extern struct asn_TYPE_descriptor_s asn_DEF_KillAllWarningMessages;
extern struct asn_TYPE_descriptor_s asn_DEF_LAC;
extern struct asn_TYPE_descriptor_s asn_DEF_LAI;
extern struct asn_TYPE_descriptor_s asn_DEF_LastVisitedCell_Item;
extern struct asn_TYPE_descriptor_s asn_DEF_LastVisitedEUTRANCellInformation;
extern struct asn_TYPE_descriptor_s asn_DEF_LastVisitedUTRANCellInformation;
extern struct asn_TYPE_descriptor_s asn_DEF_LastVisitedGERANCellInformation;
extern struct asn_TYPE_descriptor_s asn_DEF_L3_Information;
extern struct asn_TYPE_descriptor_s asn_DEF_LPPa_PDU;
extern struct asn_TYPE_descriptor_s asn_DEF_LHN_ID;
extern struct asn_TYPE_descriptor_s asn_DEF_Links_to_log;
extern struct asn_TYPE_descriptor_s asn_DEF_ListeningSubframePattern;
extern struct asn_TYPE_descriptor_s asn_DEF_LoggedMDT;
extern struct asn_TYPE_descriptor_s asn_DEF_LoggingInterval;
extern struct asn_TYPE_descriptor_s asn_DEF_LoggingDuration;
extern struct asn_TYPE_descriptor_s asn_DEF_LoggedMBSFNMDT;
extern struct asn_TYPE_descriptor_s asn_DEF_M3Configuration;
extern struct asn_TYPE_descriptor_s asn_DEF_M3period;
extern struct asn_TYPE_descriptor_s asn_DEF_M4Configuration;
extern struct asn_TYPE_descriptor_s asn_DEF_M4period;
extern struct asn_TYPE_descriptor_s asn_DEF_M5Configuration;
extern struct asn_TYPE_descriptor_s asn_DEF_M5period;
extern struct asn_TYPE_descriptor_s asn_DEF_MDT_Activation;
extern struct asn_TYPE_descriptor_s asn_DEF_MDT_Location_Info;
extern struct asn_TYPE_descriptor_s asn_DEF_MDT_Configuration;
extern struct asn_TYPE_descriptor_s asn_DEF_ManagementBasedMDTAllowed;
extern struct asn_TYPE_descriptor_s asn_DEF_MBSFN_ResultToLog;
extern struct asn_TYPE_descriptor_s asn_DEF_MBSFN_ResultToLogInfo;
extern struct asn_TYPE_descriptor_s asn_DEF_MDTPLMNList;
extern struct asn_TYPE_descriptor_s asn_DEF_PrivacyIndicator;
extern struct asn_TYPE_descriptor_s asn_DEF_MDTMode;
extern struct asn_TYPE_descriptor_s asn_DEF_MDTMode_Extension;
extern struct asn_TYPE_descriptor_s asn_DEF_MeasurementsToActivate;
extern struct asn_TYPE_descriptor_s asn_DEF_MeasurementThresholdA2;
extern struct asn_TYPE_descriptor_s asn_DEF_MessageIdentifier;
extern struct asn_TYPE_descriptor_s asn_DEF_MobilityInformation;
extern struct asn_TYPE_descriptor_s asn_DEF_MMEname;
extern struct asn_TYPE_descriptor_s asn_DEF_MMERelaySupportIndicator;
extern struct asn_TYPE_descriptor_s asn_DEF_MME_Group_ID;
extern struct asn_TYPE_descriptor_s asn_DEF_MME_Code;
extern struct asn_TYPE_descriptor_s asn_DEF_MME_UE_S1AP_ID;
extern struct asn_TYPE_descriptor_s asn_DEF_M_TMSI;
extern struct asn_TYPE_descriptor_s asn_DEF_MSClassmark2;
extern struct asn_TYPE_descriptor_s asn_DEF_MSClassmark3;
extern struct asn_TYPE_descriptor_s asn_DEF_MutingAvailabilityIndication;
extern struct asn_TYPE_descriptor_s asn_DEF_MutingPatternInformation;
extern struct asn_TYPE_descriptor_s asn_DEF_NAS_PDU;
extern struct asn_TYPE_descriptor_s asn_DEF_NASSecurityParametersfromE_UTRAN;
extern struct asn_TYPE_descriptor_s asn_DEF_NASSecurityParameterstoE_UTRAN;
extern struct asn_TYPE_descriptor_s asn_DEF_NumberofBroadcastRequest;
extern struct asn_TYPE_descriptor_s asn_DEF_NumberOfBroadcasts;
extern struct asn_TYPE_descriptor_s asn_DEF_OldBSS_ToNewBSS_Information;
extern struct asn_TYPE_descriptor_s asn_DEF_OverloadAction;
extern struct asn_TYPE_descriptor_s asn_DEF_OverloadResponse;
extern struct asn_TYPE_descriptor_s asn_DEF_PagingDRX;
extern struct asn_TYPE_descriptor_s asn_DEF_PagingPriority;
extern struct asn_TYPE_descriptor_s asn_DEF_PDCP_SN;
extern struct asn_TYPE_descriptor_s asn_DEF_PDCP_SNExtended;
extern struct asn_TYPE_descriptor_s asn_DEF_M1PeriodicReporting;
extern struct asn_TYPE_descriptor_s asn_DEF_PLMNidentity;
extern struct asn_TYPE_descriptor_s asn_DEF_Port_Number;
extern struct asn_TYPE_descriptor_s asn_DEF_Pre_emptionCapability;
extern struct asn_TYPE_descriptor_s asn_DEF_Pre_emptionVulnerability;
extern struct asn_TYPE_descriptor_s asn_DEF_PriorityLevel;
extern struct asn_TYPE_descriptor_s asn_DEF_ProSeAuthorized;
extern struct asn_TYPE_descriptor_s asn_DEF_ProSeDirectDiscovery;
extern struct asn_TYPE_descriptor_s asn_DEF_ProSeDirectCommunication;
extern struct asn_TYPE_descriptor_s asn_DEF_PS_ServiceNotAvailable;
extern struct asn_TYPE_descriptor_s asn_DEF_QCI;
extern struct asn_TYPE_descriptor_s asn_DEF_ReceiveStatusofULPDCPSDUs;
extern struct asn_TYPE_descriptor_s asn_DEF_ReceiveStatusOfULPDCPSDUsExtended;
extern struct asn_TYPE_descriptor_s asn_DEF_RelativeMMECapacity;
extern struct asn_TYPE_descriptor_s asn_DEF_RelayNode_Indicator;
extern struct asn_TYPE_descriptor_s asn_DEF_RAC;
extern struct asn_TYPE_descriptor_s asn_DEF_ReportAmountMDT;
extern struct asn_TYPE_descriptor_s asn_DEF_ReportIntervalMDT;
extern struct asn_TYPE_descriptor_s asn_DEF_M1ReportingTrigger;
extern struct asn_TYPE_descriptor_s asn_DEF_RequestType;
extern struct asn_TYPE_descriptor_s asn_DEF_RIMTransfer;
extern struct asn_TYPE_descriptor_s asn_DEF_RIMInformation;
extern struct asn_TYPE_descriptor_s asn_DEF_RIMRoutingAddress;
extern struct asn_TYPE_descriptor_s asn_DEF_ReportArea;
extern struct asn_TYPE_descriptor_s asn_DEF_RepetitionPeriod;
extern struct asn_TYPE_descriptor_s asn_DEF_RLFReportInformation;
extern struct asn_TYPE_descriptor_s asn_DEF_RNC_ID;
extern struct asn_TYPE_descriptor_s asn_DEF_RRC_Container;
extern struct asn_TYPE_descriptor_s asn_DEF_RRC_Establishment_Cause;
extern struct asn_TYPE_descriptor_s asn_DEF_ECGIListForRestart;
extern struct asn_TYPE_descriptor_s asn_DEF_Routing_ID;
extern struct asn_TYPE_descriptor_s asn_DEF_SecurityKey;
extern struct asn_TYPE_descriptor_s asn_DEF_SecurityContext;
extern struct asn_TYPE_descriptor_s asn_DEF_SerialNumber;
extern struct asn_TYPE_descriptor_s asn_DEF_SONInformation;
extern struct asn_TYPE_descriptor_s asn_DEF_SONInformation_Extension;
extern struct asn_TYPE_descriptor_s asn_DEF_SONInformationRequest;
extern struct asn_TYPE_descriptor_s asn_DEF_SONInformationReply;
extern struct asn_TYPE_descriptor_s asn_DEF_SONInformationReport;
extern struct asn_TYPE_descriptor_s asn_DEF_SONConfigurationTransfer;
extern struct asn_TYPE_descriptor_s asn_DEF_SynchronisationInformation;
extern struct asn_TYPE_descriptor_s asn_DEF_Source_ToTarget_TransparentContainer;
extern struct asn_TYPE_descriptor_s asn_DEF_SourceBSS_ToTargetBSS_TransparentContainer;
extern struct asn_TYPE_descriptor_s asn_DEF_SourceeNB_ID;
extern struct asn_TYPE_descriptor_s asn_DEF_SRVCCOperationPossible;
extern struct asn_TYPE_descriptor_s asn_DEF_SRVCCHOIndication;
extern struct asn_TYPE_descriptor_s asn_DEF_SourceeNB_ToTargeteNB_TransparentContainer;
extern struct asn_TYPE_descriptor_s asn_DEF_SourceRNC_ToTargetRNC_TransparentContainer;
extern struct asn_TYPE_descriptor_s asn_DEF_ServedGUMMEIs;
extern struct asn_TYPE_descriptor_s asn_DEF_ServedGUMMEIsItem;
extern struct asn_TYPE_descriptor_s asn_DEF_ServedGroupIDs;
extern struct asn_TYPE_descriptor_s asn_DEF_ServedMMECs;
extern struct asn_TYPE_descriptor_s asn_DEF_ServedPLMNs;
extern struct asn_TYPE_descriptor_s asn_DEF_SubscriberProfileIDforRFP;
extern struct asn_TYPE_descriptor_s asn_DEF_SupportedTAs;
extern struct asn_TYPE_descriptor_s asn_DEF_SupportedTAs_Item;
extern struct asn_TYPE_descriptor_s asn_DEF_StratumLevel;
extern struct asn_TYPE_descriptor_s asn_DEF_SynchronisationStatus;
extern struct asn_TYPE_descriptor_s asn_DEF_TimeSynchronisationInfo;
extern struct asn_TYPE_descriptor_s asn_DEF_S_TMSI;
extern struct asn_TYPE_descriptor_s asn_DEF_TAC;
extern struct asn_TYPE_descriptor_s asn_DEF_TAIBasedMDT;
extern struct asn_TYPE_descriptor_s asn_DEF_TAIListforMDT;
extern struct asn_TYPE_descriptor_s asn_DEF_TAIListforWarning;
extern struct asn_TYPE_descriptor_s asn_DEF_TAI;
extern struct asn_TYPE_descriptor_s asn_DEF_TAI_Broadcast;
extern struct asn_TYPE_descriptor_s asn_DEF_TAI_Broadcast_Item;
extern struct asn_TYPE_descriptor_s asn_DEF_TAI_Cancelled;
extern struct asn_TYPE_descriptor_s asn_DEF_TAI_Cancelled_Item;
extern struct asn_TYPE_descriptor_s asn_DEF_TABasedMDT;
extern struct asn_TYPE_descriptor_s asn_DEF_TAListforMDT;
extern struct asn_TYPE_descriptor_s asn_DEF_CompletedCellinTAI;
extern struct asn_TYPE_descriptor_s asn_DEF_CompletedCellinTAI_Item;
extern struct asn_TYPE_descriptor_s asn_DEF_TBCD_STRING;
extern struct asn_TYPE_descriptor_s asn_DEF_TargetID;
extern struct asn_TYPE_descriptor_s asn_DEF_TargeteNB_ID;
extern struct asn_TYPE_descriptor_s asn_DEF_TargetRNC_ID;
extern struct asn_TYPE_descriptor_s asn_DEF_TargeteNB_ToSourceeNB_TransparentContainer;
extern struct asn_TYPE_descriptor_s asn_DEF_Target_ToSource_TransparentContainer;
extern struct asn_TYPE_descriptor_s asn_DEF_TargetRNC_ToSourceRNC_TransparentContainer;
extern struct asn_TYPE_descriptor_s asn_DEF_TargetBSS_ToSourceBSS_TransparentContainer;
extern struct asn_TYPE_descriptor_s asn_DEF_M1ThresholdEventA2;
extern struct asn_TYPE_descriptor_s asn_DEF_Threshold_RSRP;
extern struct asn_TYPE_descriptor_s asn_DEF_Threshold_RSRQ;
extern struct asn_TYPE_descriptor_s asn_DEF_TimeToWait;
extern struct asn_TYPE_descriptor_s asn_DEF_Time_UE_StayedInCell;
extern struct asn_TYPE_descriptor_s asn_DEF_Time_UE_StayedInCell_EnhancedGranularity;
extern struct asn_TYPE_descriptor_s asn_DEF_TransportInformation;
extern struct asn_TYPE_descriptor_s asn_DEF_TransportLayerAddress;
extern struct asn_TYPE_descriptor_s asn_DEF_TraceActivation;
extern struct asn_TYPE_descriptor_s asn_DEF_TraceDepth;
extern struct asn_TYPE_descriptor_s asn_DEF_E_UTRAN_Trace_ID;
extern struct asn_TYPE_descriptor_s asn_DEF_TrafficLoadReductionIndication;
extern struct asn_TYPE_descriptor_s asn_DEF_TunnelInformation;
extern struct asn_TYPE_descriptor_s asn_DEF_TypeOfError;
extern struct asn_TYPE_descriptor_s asn_DEF_TAIListForRestart;
extern struct asn_TYPE_descriptor_s asn_DEF_UEAggregateMaximumBitrate;
extern struct asn_TYPE_descriptor_s asn_DEF_UE_S1AP_IDs;
extern struct asn_TYPE_descriptor_s asn_DEF_UE_S1AP_ID_pair;
extern struct asn_TYPE_descriptor_s asn_DEF_UE_associatedLogicalS1_ConnectionItem;
extern struct asn_TYPE_descriptor_s asn_DEF_UEIdentityIndexValue;
extern struct asn_TYPE_descriptor_s asn_DEF_UE_HistoryInformation;
extern struct asn_TYPE_descriptor_s asn_DEF_UE_HistoryInformationFromTheUE;
extern struct asn_TYPE_descriptor_s asn_DEF_UEPagingID;
extern struct asn_TYPE_descriptor_s asn_DEF_UERadioCapability;
extern struct asn_TYPE_descriptor_s asn_DEF_UERadioCapabilityForPaging;
extern struct asn_TYPE_descriptor_s asn_DEF_UE_RLF_Report_Container;
extern struct asn_TYPE_descriptor_s asn_DEF_UE_RLF_Report_Container_for_extended_bands;
extern struct asn_TYPE_descriptor_s asn_DEF_UESecurityCapabilities;
extern struct asn_TYPE_descriptor_s asn_DEF_UserLocationInformation;
extern struct asn_TYPE_descriptor_s asn_DEF_VoiceSupportMatchIndicator;
extern struct asn_TYPE_descriptor_s asn_DEF_WarningAreaList;
extern struct asn_TYPE_descriptor_s asn_DEF_WarningType;
extern struct asn_TYPE_descriptor_s asn_DEF_WarningSecurityInfo;
extern struct asn_TYPE_descriptor_s asn_DEF_WarningMessageContents;
extern struct asn_TYPE_descriptor_s asn_DEF_X2TNLConfigurationInfo;
extern struct asn_TYPE_descriptor_s asn_DEF_ENBX2ExtTLAs;
extern struct asn_TYPE_descriptor_s asn_DEF_ENBX2ExtTLA;
extern struct asn_TYPE_descriptor_s asn_DEF_ENBX2GTPTLAs;
extern struct asn_TYPE_descriptor_s asn_DEF_ENBIndirectX2TransportLayerAddresses;
extern struct asn_TYPE_descriptor_s asn_DEF_Criticality;
extern struct asn_TYPE_descriptor_s asn_DEF_Presence;
extern struct asn_TYPE_descriptor_s asn_DEF_PrivateIE_ID;
extern struct asn_TYPE_descriptor_s asn_DEF_ProcedureCode;
extern struct asn_TYPE_descriptor_s asn_DEF_ProtocolExtensionID;
extern struct asn_TYPE_descriptor_s asn_DEF_ProtocolIE_ID;
extern struct asn_TYPE_descriptor_s asn_DEF_TriggeringMessage;
extern struct asn_TYPE_descriptor_s asn_DEF_EXTERNAL;


struct asn_TYPE_descriptor_s *asn_pdu_collection[] = {
	/* From module S1AP-PDU-Descriptions in asn/s1ap_v12.asn */
	&asn_DEF_S1AP_PDU,	
	&asn_DEF_InitiatingMessage,	
	&asn_DEF_SuccessfulOutcome,	
	&asn_DEF_UnsuccessfulOutcome,	
	/* From module S1AP-PDU-Contents in asn/s1ap_v12.asn */
	&asn_DEF_HandoverRequired,	
	&asn_DEF_HandoverCommand,	
	&asn_DEF_E_RABSubjecttoDataForwardingList,	
	&asn_DEF_E_RABDataForwardingItem,	
	&asn_DEF_HandoverPreparationFailure,	
	&asn_DEF_HandoverRequest,	
	&asn_DEF_E_RABToBeSetupListHOReq,	
	&asn_DEF_E_RABToBeSetupItemHOReq,	
	&asn_DEF_HandoverRequestAcknowledge,	
	&asn_DEF_E_RABAdmittedList,	
	&asn_DEF_E_RABAdmittedItem,	
	&asn_DEF_E_RABFailedtoSetupListHOReqAck,	
	&asn_DEF_E_RABFailedToSetupItemHOReqAck,	
	&asn_DEF_HandoverFailure,	
	&asn_DEF_HandoverNotify,	
	&asn_DEF_PathSwitchRequest,	
	&asn_DEF_E_RABToBeSwitchedDLList,	
	&asn_DEF_E_RABToBeSwitchedDLItem,	
	&asn_DEF_PathSwitchRequestAcknowledge,	
	&asn_DEF_E_RABToBeSwitchedULList,	
	&asn_DEF_E_RABToBeSwitchedULItem,	
	&asn_DEF_PathSwitchRequestFailure,	
	&asn_DEF_HandoverCancel,	
	&asn_DEF_HandoverCancelAcknowledge,	
	&asn_DEF_E_RABSetupRequest,	
	&asn_DEF_E_RABToBeSetupListBearerSUReq,	
	&asn_DEF_E_RABToBeSetupItemBearerSUReq,	
	&asn_DEF_E_RABSetupResponse,	
	&asn_DEF_E_RABSetupListBearerSURes,	
	&asn_DEF_E_RABSetupItemBearerSURes,	
	&asn_DEF_E_RABModifyRequest,	
	&asn_DEF_E_RABToBeModifiedListBearerModReq,	
	&asn_DEF_E_RABToBeModifiedItemBearerModReq,	
	&asn_DEF_E_RABModifyResponse,	
	&asn_DEF_E_RABModifyListBearerModRes,	
	&asn_DEF_E_RABModifyItemBearerModRes,	
	&asn_DEF_E_RABReleaseCommand,	
	&asn_DEF_E_RABReleaseResponse,	
	&asn_DEF_E_RABReleaseListBearerRelComp,	
	&asn_DEF_E_RABReleaseItemBearerRelComp,	
	&asn_DEF_E_RABReleaseIndication,	
	&asn_DEF_InitialContextSetupRequest,	
	&asn_DEF_E_RABToBeSetupListCtxtSUReq,	
	&asn_DEF_E_RABToBeSetupItemCtxtSUReq,	
	&asn_DEF_InitialContextSetupResponse,	
	&asn_DEF_E_RABSetupListCtxtSURes,	
	&asn_DEF_E_RABSetupItemCtxtSURes,	
	&asn_DEF_InitialContextSetupFailure,	
	&asn_DEF_Paging,	
	&asn_DEF_TAIList,	
	&asn_DEF_TAIItem,	
	&asn_DEF_UEContextReleaseRequest,	
	&asn_DEF_UEContextReleaseCommand,	
	&asn_DEF_UEContextReleaseComplete,	
	&asn_DEF_UEContextModificationRequest,	
	&asn_DEF_UEContextModificationResponse,	
	&asn_DEF_UEContextModificationFailure,	
	&asn_DEF_UERadioCapabilityMatchRequest,	
	&asn_DEF_UERadioCapabilityMatchResponse,	
	&asn_DEF_DownlinkNASTransport,	
	&asn_DEF_InitialUEMessage,	
	&asn_DEF_UplinkNASTransport,	
	&asn_DEF_NASNonDeliveryIndication,	
	&asn_DEF_Reset,	
	&asn_DEF_ResetType,	
	&asn_DEF_ResetAll,	
	&asn_DEF_UE_associatedLogicalS1_ConnectionListRes,	
	&asn_DEF_ResetAcknowledge,	
	&asn_DEF_UE_associatedLogicalS1_ConnectionListResAck,	
	&asn_DEF_ErrorIndication,	
	&asn_DEF_S1SetupRequest,	
	&asn_DEF_S1SetupResponse,	
	&asn_DEF_S1SetupFailure,	
	&asn_DEF_ENBConfigurationUpdate,	
	&asn_DEF_ENBConfigurationUpdateAcknowledge,	
	&asn_DEF_ENBConfigurationUpdateFailure,	
	&asn_DEF_MMEConfigurationUpdate,	
	&asn_DEF_MMEConfigurationUpdateAcknowledge,	
	&asn_DEF_MMEConfigurationUpdateFailure,	
	&asn_DEF_DownlinkS1cdma2000tunnelling,	
	&asn_DEF_UplinkS1cdma2000tunnelling,	
	&asn_DEF_UECapabilityInfoIndication,	
	&asn_DEF_ENBStatusTransfer,	
	&asn_DEF_MMEStatusTransfer,	
	&asn_DEF_TraceStart,	
	&asn_DEF_TraceFailureIndication,	
	&asn_DEF_DeactivateTrace,	
	&asn_DEF_CellTrafficTrace,	
	&asn_DEF_LocationReportingControl,	
	&asn_DEF_LocationReportingFailureIndication,	
	&asn_DEF_LocationReport,	
	&asn_DEF_OverloadStart,	
	&asn_DEF_OverloadStop,	
	&asn_DEF_WriteReplaceWarningRequest,	
	&asn_DEF_WriteReplaceWarningResponse,	
	&asn_DEF_ENBDirectInformationTransfer,	
	&asn_DEF_Inter_SystemInformationTransferType,	
	&asn_DEF_MMEDirectInformationTransfer,	
	&asn_DEF_ENBConfigurationTransfer,	
	&asn_DEF_MMEConfigurationTransfer,	
	&asn_DEF_PrivateMessage,	
	&asn_DEF_KillRequest,	
	&asn_DEF_KillResponse,	
	&asn_DEF_PWSRestartIndication,	
	&asn_DEF_DownlinkUEAssociatedLPPaTransport,	
	&asn_DEF_UplinkUEAssociatedLPPaTransport,	
	&asn_DEF_DownlinkNonUEAssociatedLPPaTransport,	
	&asn_DEF_UplinkNonUEAssociatedLPPaTransport,	
	&asn_DEF_E_RABModificationIndication,	
	&asn_DEF_E_RABToBeModifiedListBearerModInd,	
	&asn_DEF_E_RABToBeModifiedItemBearerModInd,	
	&asn_DEF_E_RABNotToBeModifiedListBearerModInd,	
	&asn_DEF_E_RABNotToBeModifiedItemBearerModInd,	
	&asn_DEF_E_RABModificationConfirm,	
	&asn_DEF_E_RABModifyListBearerModConf,	
	&asn_DEF_E_RABModifyItemBearerModConf,	
	/* From module S1AP-IEs in asn/s1ap_v12.asn */
	&asn_DEF_AreaScopeOfMDT,	
	&asn_DEF_AllocationAndRetentionPriority,	
	&asn_DEF_Bearers_SubjectToStatusTransferList,	
	&asn_DEF_Bearers_SubjectToStatusTransfer_Item,	
	&asn_DEF_BitRate,	
	&asn_DEF_BPLMNs,	
	&asn_DEF_BroadcastCancelledAreaList,	
	&asn_DEF_BroadcastCompletedAreaList,	
	&asn_DEF_CancelledCellinEAI,	
	&asn_DEF_CancelledCellinEAI_Item,	
	&asn_DEF_CancelledCellinTAI,	
	&asn_DEF_CancelledCellinTAI_Item,	
	&asn_DEF_Cause,	
	&asn_DEF_CauseMisc,	
	&asn_DEF_CauseProtocol,	
	&asn_DEF_CauseRadioNetwork,	
	&asn_DEF_CauseTransport,	
	&asn_DEF_CauseNas,	
	&asn_DEF_CellAccessMode,	
	&asn_DEF_CellIdentity,	
	&asn_DEF_CellID_Broadcast,	
	&asn_DEF_CellID_Broadcast_Item,	
	&asn_DEF_CellID_Cancelled,	
	&asn_DEF_CellID_Cancelled_Item,	
	&asn_DEF_CellBasedMDT,	
	&asn_DEF_CellIdListforMDT,	
	&asn_DEF_Cdma2000PDU,	
	&asn_DEF_Cdma2000RATType,	
	&asn_DEF_Cdma2000SectorID,	
	&asn_DEF_Cdma2000HOStatus,	
	&asn_DEF_Cdma2000HORequiredIndication,	
	&asn_DEF_Cdma2000OneXSRVCCInfo,	
	&asn_DEF_Cdma2000OneXMEID,	
	&asn_DEF_Cdma2000OneXMSI,	
	&asn_DEF_Cdma2000OneXPilot,	
	&asn_DEF_Cdma2000OneXRAND,	
	&asn_DEF_Cell_Size,	
	&asn_DEF_CellType,	
	&asn_DEF_CGI,	
	&asn_DEF_CI,	
	&asn_DEF_CNDomain,	
	&asn_DEF_ConcurrentWarningMessageIndicator,	
	&asn_DEF_Correlation_ID,	
	&asn_DEF_CSFallbackIndicator,	
	&asn_DEF_AdditionalCSFallbackIndicator,	
	&asn_DEF_CSG_Id,	
	&asn_DEF_CSG_IdList,	
	&asn_DEF_CSG_IdList_Item,	
	&asn_DEF_CSGMembershipStatus,	
	&asn_DEF_COUNTvalue,	
	&asn_DEF_COUNTValueExtended,	
	&asn_DEF_CriticalityDiagnostics,	
	&asn_DEF_CriticalityDiagnostics_IE_List,	
	&asn_DEF_CriticalityDiagnostics_IE_Item,	
	&asn_DEF_DataCodingScheme,	
	&asn_DEF_DL_Forwarding,	
	&asn_DEF_Direct_Forwarding_Path_Availability,	
	&asn_DEF_Data_Forwarding_Not_Possible,	
	&asn_DEF_EARFCN,	
	&asn_DEF_ECGIList,	
	&asn_DEF_EmergencyAreaIDList,	
	&asn_DEF_EmergencyAreaID,	
	&asn_DEF_EmergencyAreaID_Broadcast,	
	&asn_DEF_EmergencyAreaID_Broadcast_Item,	
	&asn_DEF_EmergencyAreaID_Cancelled,	
	&asn_DEF_EmergencyAreaID_Cancelled_Item,	
	&asn_DEF_CompletedCellinEAI,	
	&asn_DEF_CompletedCellinEAI_Item,	
	&asn_DEF_ECGI_List,	
	&asn_DEF_EmergencyAreaIDListForRestart,	
	&asn_DEF_ENB_ID,	
	&asn_DEF_GERAN_Cell_ID,	
	&asn_DEF_Global_ENB_ID,	
	&asn_DEF_GUMMEIList,	
	&asn_DEF_ENB_StatusTransfer_TransparentContainer,	
	&asn_DEF_ENB_UE_S1AP_ID,	
	&asn_DEF_ENBname,	
	&asn_DEF_ENBX2TLAs,	
	&asn_DEF_EncryptionAlgorithms,	
	&asn_DEF_EPLMNs,	
	&asn_DEF_EventType,	
	&asn_DEF_E_RAB_ID,	
	&asn_DEF_E_RABInformationList,	
	&asn_DEF_E_RABInformationListItem,	
	&asn_DEF_E_RABList,	
	&asn_DEF_E_RABItem,	
	&asn_DEF_E_RABLevelQoSParameters,	
	&asn_DEF_EUTRAN_CGI,	
	&asn_DEF_EUTRANRoundTripDelayEstimationInfo,	
	&asn_DEF_ExpectedUEBehaviour,	
	&asn_DEF_ExpectedUEActivityBehaviour,	
	&asn_DEF_ExpectedActivityPeriod,	
	&asn_DEF_ExpectedIdlePeriod,	
	&asn_DEF_SourceOfUEActivityBehaviourInformation,	
	&asn_DEF_ExpectedHOInterval,	
	&asn_DEF_ExtendedRNC_ID,	
	&asn_DEF_ExtendedRepetitionPeriod,	
	&asn_DEF_ForbiddenInterRATs,	
	&asn_DEF_ForbiddenTAs,	
	&asn_DEF_ForbiddenTAs_Item,	
	&asn_DEF_ForbiddenTACs,	
	&asn_DEF_ForbiddenLAs,	
	&asn_DEF_ForbiddenLAs_Item,	
	&asn_DEF_ForbiddenLACs,	
	&asn_DEF_GBR_QosInformation,	
	&asn_DEF_GTP_TEID,	
	&asn_DEF_GUMMEI,	
	&asn_DEF_GUMMEIType,	
	&asn_DEF_GWContextReleaseIndication,	
	&asn_DEF_HandoverRestrictionList,	
	&asn_DEF_HandoverType,	
	&asn_DEF_HFN,	
	&asn_DEF_HFNModified,	
	&asn_DEF_Masked_IMEISV,	
	&asn_DEF_ImmediateMDT,	
	&asn_DEF_IMSI,	
	&asn_DEF_IntegrityProtectionAlgorithms,	
	&asn_DEF_InterfacesToTrace,	
	&asn_DEF_KillAllWarningMessages,	
	&asn_DEF_LAC,	
	&asn_DEF_LAI,	
	&asn_DEF_LastVisitedCell_Item,	
	&asn_DEF_LastVisitedEUTRANCellInformation,	
	&asn_DEF_LastVisitedUTRANCellInformation,	
	&asn_DEF_LastVisitedGERANCellInformation,	
	&asn_DEF_L3_Information,	
	&asn_DEF_LPPa_PDU,	
	&asn_DEF_LHN_ID,	
	&asn_DEF_Links_to_log,	
	&asn_DEF_ListeningSubframePattern,	
	&asn_DEF_LoggedMDT,	
	&asn_DEF_LoggingInterval,	
	&asn_DEF_LoggingDuration,	
	&asn_DEF_LoggedMBSFNMDT,	
	&asn_DEF_M3Configuration,	
	&asn_DEF_M3period,	
	&asn_DEF_M4Configuration,	
	&asn_DEF_M4period,	
	&asn_DEF_M5Configuration,	
	&asn_DEF_M5period,	
	&asn_DEF_MDT_Activation,	
	&asn_DEF_MDT_Location_Info,	
	&asn_DEF_MDT_Configuration,	
	&asn_DEF_ManagementBasedMDTAllowed,	
	&asn_DEF_MBSFN_ResultToLog,	
	&asn_DEF_MBSFN_ResultToLogInfo,	
	&asn_DEF_MDTPLMNList,	
	&asn_DEF_PrivacyIndicator,	
	&asn_DEF_MDTMode,	
	&asn_DEF_MDTMode_Extension,	
	&asn_DEF_MeasurementsToActivate,	
	&asn_DEF_MeasurementThresholdA2,	
	&asn_DEF_MessageIdentifier,	
	&asn_DEF_MobilityInformation,	
	&asn_DEF_MMEname,	
	&asn_DEF_MMERelaySupportIndicator,	
	&asn_DEF_MME_Group_ID,	
	&asn_DEF_MME_Code,	
	&asn_DEF_MME_UE_S1AP_ID,	
	&asn_DEF_M_TMSI,	
	&asn_DEF_MSClassmark2,	
	&asn_DEF_MSClassmark3,	
	&asn_DEF_MutingAvailabilityIndication,	
	&asn_DEF_MutingPatternInformation,	
	&asn_DEF_NAS_PDU,	
	&asn_DEF_NASSecurityParametersfromE_UTRAN,	
	&asn_DEF_NASSecurityParameterstoE_UTRAN,	
	&asn_DEF_NumberofBroadcastRequest,	
	&asn_DEF_NumberOfBroadcasts,	
	&asn_DEF_OldBSS_ToNewBSS_Information,	
	&asn_DEF_OverloadAction,	
	&asn_DEF_OverloadResponse,	
	&asn_DEF_PagingDRX,	
	&asn_DEF_PagingPriority,	
	&asn_DEF_PDCP_SN,	
	&asn_DEF_PDCP_SNExtended,	
	&asn_DEF_M1PeriodicReporting,	
	&asn_DEF_PLMNidentity,	
	&asn_DEF_Port_Number,	
	&asn_DEF_Pre_emptionCapability,	
	&asn_DEF_Pre_emptionVulnerability,	
	&asn_DEF_PriorityLevel,	
	&asn_DEF_ProSeAuthorized,	
	&asn_DEF_ProSeDirectDiscovery,	
	&asn_DEF_ProSeDirectCommunication,	
	&asn_DEF_PS_ServiceNotAvailable,	
	&asn_DEF_QCI,	
	&asn_DEF_ReceiveStatusofULPDCPSDUs,	
	&asn_DEF_ReceiveStatusOfULPDCPSDUsExtended,	
	&asn_DEF_RelativeMMECapacity,	
	&asn_DEF_RelayNode_Indicator,	
	&asn_DEF_RAC,	
	&asn_DEF_ReportAmountMDT,	
	&asn_DEF_ReportIntervalMDT,	
	&asn_DEF_M1ReportingTrigger,	
	&asn_DEF_RequestType,	
	&asn_DEF_RIMTransfer,	
	&asn_DEF_RIMInformation,	
	&asn_DEF_RIMRoutingAddress,	
	&asn_DEF_ReportArea,	
	&asn_DEF_RepetitionPeriod,	
	&asn_DEF_RLFReportInformation,	
	&asn_DEF_RNC_ID,	
	&asn_DEF_RRC_Container,	
	&asn_DEF_RRC_Establishment_Cause,	
	&asn_DEF_ECGIListForRestart,	
	&asn_DEF_Routing_ID,	
	&asn_DEF_SecurityKey,	
	&asn_DEF_SecurityContext,	
	&asn_DEF_SerialNumber,	
	&asn_DEF_SONInformation,	
	&asn_DEF_SONInformation_Extension,	
	&asn_DEF_SONInformationRequest,	
	&asn_DEF_SONInformationReply,	
	&asn_DEF_SONInformationReport,	
	&asn_DEF_SONConfigurationTransfer,	
	&asn_DEF_SynchronisationInformation,	
	&asn_DEF_Source_ToTarget_TransparentContainer,	
	&asn_DEF_SourceBSS_ToTargetBSS_TransparentContainer,	
	&asn_DEF_SourceeNB_ID,	
	&asn_DEF_SRVCCOperationPossible,	
	&asn_DEF_SRVCCHOIndication,	
	&asn_DEF_SourceeNB_ToTargeteNB_TransparentContainer,	
	&asn_DEF_SourceRNC_ToTargetRNC_TransparentContainer,	
	&asn_DEF_ServedGUMMEIs,	
	&asn_DEF_ServedGUMMEIsItem,	
	&asn_DEF_ServedGroupIDs,	
	&asn_DEF_ServedMMECs,	
	&asn_DEF_ServedPLMNs,	
	&asn_DEF_SubscriberProfileIDforRFP,	
	&asn_DEF_SupportedTAs,	
	&asn_DEF_SupportedTAs_Item,	
	&asn_DEF_StratumLevel,	
	&asn_DEF_SynchronisationStatus,	
	&asn_DEF_TimeSynchronisationInfo,	
	&asn_DEF_S_TMSI,	
	&asn_DEF_TAC,	
	&asn_DEF_TAIBasedMDT,	
	&asn_DEF_TAIListforMDT,	
	&asn_DEF_TAIListforWarning,	
	&asn_DEF_TAI,	
	&asn_DEF_TAI_Broadcast,	
	&asn_DEF_TAI_Broadcast_Item,	
	&asn_DEF_TAI_Cancelled,	
	&asn_DEF_TAI_Cancelled_Item,	
	&asn_DEF_TABasedMDT,	
	&asn_DEF_TAListforMDT,	
	&asn_DEF_CompletedCellinTAI,	
	&asn_DEF_CompletedCellinTAI_Item,	
	&asn_DEF_TBCD_STRING,	
	&asn_DEF_TargetID,	
	&asn_DEF_TargeteNB_ID,	
	&asn_DEF_TargetRNC_ID,	
	&asn_DEF_TargeteNB_ToSourceeNB_TransparentContainer,	
	&asn_DEF_Target_ToSource_TransparentContainer,	
	&asn_DEF_TargetRNC_ToSourceRNC_TransparentContainer,	
	&asn_DEF_TargetBSS_ToSourceBSS_TransparentContainer,	
	&asn_DEF_M1ThresholdEventA2,	
	&asn_DEF_Threshold_RSRP,	
	&asn_DEF_Threshold_RSRQ,	
	&asn_DEF_TimeToWait,	
	&asn_DEF_Time_UE_StayedInCell,	
	&asn_DEF_Time_UE_StayedInCell_EnhancedGranularity,	
	&asn_DEF_TransportInformation,	
	&asn_DEF_TransportLayerAddress,	
	&asn_DEF_TraceActivation,	
	&asn_DEF_TraceDepth,	
	&asn_DEF_E_UTRAN_Trace_ID,	
	&asn_DEF_TrafficLoadReductionIndication,	
	&asn_DEF_TunnelInformation,	
	&asn_DEF_TypeOfError,	
	&asn_DEF_TAIListForRestart,	
	&asn_DEF_UEAggregateMaximumBitrate,	
	&asn_DEF_UE_S1AP_IDs,	
	&asn_DEF_UE_S1AP_ID_pair,	
	&asn_DEF_UE_associatedLogicalS1_ConnectionItem,	
	&asn_DEF_UEIdentityIndexValue,	
	&asn_DEF_UE_HistoryInformation,	
	&asn_DEF_UE_HistoryInformationFromTheUE,	
	&asn_DEF_UEPagingID,	
	&asn_DEF_UERadioCapability,	
	&asn_DEF_UERadioCapabilityForPaging,	
	&asn_DEF_UE_RLF_Report_Container,	
	&asn_DEF_UE_RLF_Report_Container_for_extended_bands,	
	&asn_DEF_UESecurityCapabilities,	
	&asn_DEF_UserLocationInformation,	
	&asn_DEF_VoiceSupportMatchIndicator,	
	&asn_DEF_WarningAreaList,	
	&asn_DEF_WarningType,	
	&asn_DEF_WarningSecurityInfo,	
	&asn_DEF_WarningMessageContents,	
	&asn_DEF_X2TNLConfigurationInfo,	
	&asn_DEF_ENBX2ExtTLAs,	
	&asn_DEF_ENBX2ExtTLA,	
	&asn_DEF_ENBX2GTPTLAs,	
	&asn_DEF_ENBIndirectX2TransportLayerAddresses,	
	/* From module S1AP-CommonDataTypes in asn/s1ap_v12.asn */
	&asn_DEF_Criticality,	
	&asn_DEF_Presence,	
	&asn_DEF_PrivateIE_ID,	
	&asn_DEF_ProcedureCode,	
	&asn_DEF_ProtocolExtensionID,	
	&asn_DEF_ProtocolIE_ID,	
	&asn_DEF_TriggeringMessage,	
	/* From module ASN1C-UsefulInformationObjectClasses in /usr/local/share/asn1c/standard-modules/ASN1C-UsefulInformationObjectClasses.asn1 */
	&asn_DEF_EXTERNAL,	
	0
};

