/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-Containers"
 * 	found in "asn/s1ap_v12.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER -D include/`
 */

#include "ProtocolIE-SingleContainer.h"

/*
 * This type is implemented using E_RABToBeSetupItemBearerSUReqIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using E_RABSetupItemBearerSUResIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using E_RABToBeModifiedItemBearerModReqIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using E_RABModifyItemBearerModResIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using E_RABReleaseItemBearerRelCompIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using E_RABToBeSetupItemCtxtSUReqIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using E_RABSetupItemCtxtSUResIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using TAIItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using UE_associatedLogicalS1_ConnectionItemRes,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using UE_associatedLogicalS1_ConnectionItemResAck,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using E_RABModifyItemBearerModConfIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using Bearers_SubjectToStatusTransfer_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using E_RABInformationListIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using E_RABItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using MDTMode_ExtensionIE,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using SONInformation_ExtensionIE,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using E_RABDataForwardingItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using E_RABToBeSetupItemHOReqIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using E_RABAdmittedItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using E_RABFailedtoSetupItemHOReqAckIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using E_RABToBeSwitchedDLItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using E_RABToBeSwitchedULItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using E_RABToBeModifiedItemBearerModIndIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using E_RABNotToBeModifiedItemBearerModIndIEs,
 * so here we adjust the DEF accordingly.
 */
static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_5541P0_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_5541P0 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_5541P0_tags_1,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_5541P0_tags_1)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_5541P0_tags_1[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_5541P0_tags_1,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_5541P0_tags_1)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_5541P0_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_E_RABToBeSetupItemBearerSUReqIEs_1,
	3,	/* Elements count */
	&asn_SPC_E_RABToBeSetupItemBearerSUReqIEs_specs_1	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_5541P1_tags_2[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_5541P1 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_5541P1_tags_2,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_5541P1_tags_2)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_5541P1_tags_2[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_5541P1_tags_2,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_5541P1_tags_2)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_5541P1_tags_2[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_E_RABSetupItemBearerSUResIEs_5,
	3,	/* Elements count */
	&asn_SPC_E_RABSetupItemBearerSUResIEs_specs_5	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_5541P2_tags_3[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_5541P2 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_5541P2_tags_3,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_5541P2_tags_3)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_5541P2_tags_3[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_5541P2_tags_3,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_5541P2_tags_3)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_5541P2_tags_3[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_E_RABToBeModifiedItemBearerModReqIEs_9,
	3,	/* Elements count */
	&asn_SPC_E_RABToBeModifiedItemBearerModReqIEs_specs_9	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_5541P3_tags_4[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_5541P3 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_5541P3_tags_4,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_5541P3_tags_4)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_5541P3_tags_4[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_5541P3_tags_4,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_5541P3_tags_4)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_5541P3_tags_4[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_E_RABModifyItemBearerModResIEs_13,
	3,	/* Elements count */
	&asn_SPC_E_RABModifyItemBearerModResIEs_specs_13	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_5541P4_tags_5[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_5541P4 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_5541P4_tags_5,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_5541P4_tags_5)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_5541P4_tags_5[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_5541P4_tags_5,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_5541P4_tags_5)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_5541P4_tags_5[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_E_RABReleaseItemBearerRelCompIEs_17,
	3,	/* Elements count */
	&asn_SPC_E_RABReleaseItemBearerRelCompIEs_specs_17	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_5541P5_tags_6[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_5541P5 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_5541P5_tags_6,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_5541P5_tags_6)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_5541P5_tags_6[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_5541P5_tags_6,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_5541P5_tags_6)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_5541P5_tags_6[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_E_RABToBeSetupItemCtxtSUReqIEs_21,
	3,	/* Elements count */
	&asn_SPC_E_RABToBeSetupItemCtxtSUReqIEs_specs_21	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_5541P6_tags_7[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_5541P6 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_5541P6_tags_7,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_5541P6_tags_7)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_5541P6_tags_7[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_5541P6_tags_7,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_5541P6_tags_7)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_5541P6_tags_7[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_E_RABSetupItemCtxtSUResIEs_25,
	3,	/* Elements count */
	&asn_SPC_E_RABSetupItemCtxtSUResIEs_specs_25	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_5541P7_tags_8[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_5541P7 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_5541P7_tags_8,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_5541P7_tags_8)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_5541P7_tags_8[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_5541P7_tags_8,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_5541P7_tags_8)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_5541P7_tags_8[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_TAIItemIEs_29,
	3,	/* Elements count */
	&asn_SPC_TAIItemIEs_specs_29	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_5541P8_tags_9[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_5541P8 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_5541P8_tags_9,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_5541P8_tags_9)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_5541P8_tags_9[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_5541P8_tags_9,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_5541P8_tags_9)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_5541P8_tags_9[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_UE_associatedLogicalS1_ConnectionItemRes_33,
	3,	/* Elements count */
	&asn_SPC_UE_associatedLogicalS1_ConnectionItemRes_specs_33	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_5541P9_tags_10[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_5541P9 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_5541P9_tags_10,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_5541P9_tags_10)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_5541P9_tags_10[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_5541P9_tags_10,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_5541P9_tags_10)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_5541P9_tags_10[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_UE_associatedLogicalS1_ConnectionItemResAck_37,
	3,	/* Elements count */
	&asn_SPC_UE_associatedLogicalS1_ConnectionItemResAck_specs_37	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_5541P10_tags_11[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_5541P10 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_5541P10_tags_11,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_5541P10_tags_11)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_5541P10_tags_11[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_5541P10_tags_11,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_5541P10_tags_11)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_5541P10_tags_11[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_E_RABModifyItemBearerModConfIEs_41,
	3,	/* Elements count */
	&asn_SPC_E_RABModifyItemBearerModConfIEs_specs_41	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_5541P11_tags_12[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_5541P11 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_5541P11_tags_12,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_5541P11_tags_12)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_5541P11_tags_12[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_5541P11_tags_12,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_5541P11_tags_12)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_5541P11_tags_12[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_Bearers_SubjectToStatusTransfer_ItemIEs_45,
	3,	/* Elements count */
	&asn_SPC_Bearers_SubjectToStatusTransfer_ItemIEs_specs_45	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_5541P12_tags_13[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_5541P12 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_5541P12_tags_13,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_5541P12_tags_13)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_5541P12_tags_13[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_5541P12_tags_13,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_5541P12_tags_13)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_5541P12_tags_13[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_E_RABInformationListIEs_49,
	3,	/* Elements count */
	&asn_SPC_E_RABInformationListIEs_specs_49	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_5541P13_tags_14[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_5541P13 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_5541P13_tags_14,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_5541P13_tags_14)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_5541P13_tags_14[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_5541P13_tags_14,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_5541P13_tags_14)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_5541P13_tags_14[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_E_RABItemIEs_53,
	3,	/* Elements count */
	&asn_SPC_E_RABItemIEs_specs_53	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_5541P14_tags_15[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_5541P14 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_5541P14_tags_15,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_5541P14_tags_15)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_5541P14_tags_15[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_5541P14_tags_15,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_5541P14_tags_15)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_5541P14_tags_15[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_MDTMode_ExtensionIE_57,
	3,	/* Elements count */
	&asn_SPC_MDTMode_ExtensionIE_specs_57	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_5541P15_tags_16[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_5541P15 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_5541P15_tags_16,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_5541P15_tags_16)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_5541P15_tags_16[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_5541P15_tags_16,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_5541P15_tags_16)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_5541P15_tags_16[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_SONInformation_ExtensionIE_61,
	3,	/* Elements count */
	&asn_SPC_SONInformation_ExtensionIE_specs_61	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_5541P16_tags_17[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_5541P16 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_5541P16_tags_17,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_5541P16_tags_17)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_5541P16_tags_17[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_5541P16_tags_17,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_5541P16_tags_17)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_5541P16_tags_17[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_E_RABDataForwardingItemIEs_369,
	3,	/* Elements count */
	&asn_SPC_E_RABDataForwardingItemIEs_specs_369	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_5541P17_tags_18[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_5541P17 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_5541P17_tags_18,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_5541P17_tags_18)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_5541P17_tags_18[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_5541P17_tags_18,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_5541P17_tags_18)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_5541P17_tags_18[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_E_RABToBeSetupItemHOReqIEs_373,
	3,	/* Elements count */
	&asn_SPC_E_RABToBeSetupItemHOReqIEs_specs_373	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_5541P18_tags_19[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_5541P18 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_5541P18_tags_19,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_5541P18_tags_19)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_5541P18_tags_19[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_5541P18_tags_19,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_5541P18_tags_19)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_5541P18_tags_19[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_E_RABAdmittedItemIEs_377,
	3,	/* Elements count */
	&asn_SPC_E_RABAdmittedItemIEs_specs_377	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_5541P19_tags_20[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_5541P19 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_5541P19_tags_20,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_5541P19_tags_20)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_5541P19_tags_20[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_5541P19_tags_20,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_5541P19_tags_20)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_5541P19_tags_20[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_E_RABFailedtoSetupItemHOReqAckIEs_381,
	3,	/* Elements count */
	&asn_SPC_E_RABFailedtoSetupItemHOReqAckIEs_specs_381	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_5541P20_tags_21[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_5541P20 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_5541P20_tags_21,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_5541P20_tags_21)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_5541P20_tags_21[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_5541P20_tags_21,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_5541P20_tags_21)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_5541P20_tags_21[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_E_RABToBeSwitchedDLItemIEs_385,
	3,	/* Elements count */
	&asn_SPC_E_RABToBeSwitchedDLItemIEs_specs_385	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_5541P21_tags_22[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_5541P21 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_5541P21_tags_22,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_5541P21_tags_22)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_5541P21_tags_22[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_5541P21_tags_22,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_5541P21_tags_22)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_5541P21_tags_22[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_E_RABToBeSwitchedULItemIEs_389,
	3,	/* Elements count */
	&asn_SPC_E_RABToBeSwitchedULItemIEs_specs_389	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_5541P22_tags_23[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_5541P22 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_5541P22_tags_23,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_5541P22_tags_23)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_5541P22_tags_23[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_5541P22_tags_23,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_5541P22_tags_23)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_5541P22_tags_23[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_E_RABToBeModifiedItemBearerModIndIEs_393,
	3,	/* Elements count */
	&asn_SPC_E_RABToBeModifiedItemBearerModIndIEs_specs_393	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_5541P23_tags_24[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_5541P23 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_5541P23_tags_24,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_5541P23_tags_24)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_5541P23_tags_24[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_5541P23_tags_24,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_5541P23_tags_24)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_5541P23_tags_24[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_E_RABNotToBeModifiedItemBearerModIndIEs_397,
	3,	/* Elements count */
	&asn_SPC_E_RABNotToBeModifiedItemBearerModIndIEs_specs_397	/* Additional specs */
};

