/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-Containers"
 * 	found in "asn/s1ap_v12.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER -D include/`
 */

#ifndef	_ProtocolExtensionContainer_H_
#define	_ProtocolExtensionContainer_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct E_RABDataForwardingItem_ExtIEs;
struct E_RABToBeSetupItemHOReq_ExtIEs;
struct E_RABAdmittedItem_ExtIEs;
struct E_RABFailedToSetupItemHOReqAckExtIEs;
struct E_RABToBeSwitchedDLItem_ExtIEs;
struct E_RABToBeSwitchedULItem_ExtIEs;
struct E_RABToBeSetupItemBearerSUReqExtIEs;
struct E_RABSetupItemBearerSUResExtIEs;
struct E_RABToBeModifyItemBearerModReqExtIEs;
struct E_RABModifyItemBearerModResExtIEs;
struct E_RABReleaseItemBearerRelCompExtIEs;
struct E_RABToBeSetupItemCtxtSUReqExtIEs;
struct E_RABSetupItemCtxtSUResExtIEs;
struct TAIItemExtIEs;
struct E_RABToBeModifiedItemBearerModInd_ExtIEs;
struct E_RABNotToBeModifiedItemBearerModInd_ExtIEs;
struct E_RABModifyItemBearerModConfExtIEs;
struct AllocationAndRetentionPriority_ExtIEs;
struct Bearers_SubjectToStatusTransfer_ItemExtIEs;
struct CancelledCellinEAI_Item_ExtIEs;
struct CancelledCellinTAI_Item_ExtIEs;
struct CellID_Broadcast_Item_ExtIEs;
struct CellID_Cancelled_Item_ExtIEs;
struct CellBasedMDT_ExtIEs;
struct Cdma2000OneXSRVCCInfo_ExtIEs;
struct CellType_ExtIEs;
struct CGI_ExtIEs;
struct CSG_IdList_Item_ExtIEs;
struct COUNTvalue_ExtIEs;
struct COUNTValueExtended_ExtIEs;
struct CriticalityDiagnostics_ExtIEs;
struct CriticalityDiagnostics_IE_Item_ExtIEs;
struct EmergencyAreaID_Broadcast_Item_ExtIEs;
struct EmergencyAreaID_Cancelled_Item_ExtIEs;
struct CompletedCellinEAI_Item_ExtIEs;
struct GERAN_Cell_ID_ExtIEs;
struct GlobalENB_ID_ExtIEs;
struct ENB_StatusTransfer_TransparentContainer_ExtIEs;
struct E_RABInformationListItem_ExtIEs;
struct E_RABItem_ExtIEs;
struct E_RABQoSParameters_ExtIEs;
struct EUTRAN_CGI_ExtIEs;
struct ExpectedUEBehaviour_ExtIEs;
struct ExpectedUEActivityBehaviour_ExtIEs;
struct ForbiddenTAs_Item_ExtIEs;
struct ForbiddenLAs_Item_ExtIEs;
struct GBR_QosInformation_ExtIEs;
struct GUMMEI_ExtIEs;
struct HandoverRestrictionList_ExtIEs;
struct ImmediateMDT_ExtIEs;
struct LAI_ExtIEs;
struct LastVisitedEUTRANCellInformation_ExtIEs;
struct ListeningSubframePattern_ExtIEs;
struct LoggedMDT_ExtIEs;
struct LoggedMBSFNMDT_ExtIEs;
struct M3Configuration_ExtIEs;
struct M4Configuration_ExtIEs;
struct M5Configuration_ExtIEs;
struct MDT_Configuration_ExtIEs;
struct MBSFN_ResultToLogInfo_ExtIEs;
struct MutingPatternInformation_ExtIEs;
struct M1PeriodicReporting_ExtIEs;
struct ProSeAuthorized_ExtIEs;
struct RequestType_ExtIEs;
struct RIMTransfer_ExtIEs;
struct RLFReportInformation_ExtIEs;
struct SecurityContext_ExtIEs;
struct SONInformationReply_ExtIEs;
struct SONConfigurationTransfer_ExtIEs;
struct SynchronisationInformation_ExtIEs;
struct SourceeNB_ID_ExtIEs;
struct SourceeNB_ToTargeteNB_TransparentContainer_ExtIEs;
struct ServedGUMMEIsItem_ExtIEs;
struct SupportedTAs_Item_ExtIEs;
struct TimeSynchronisationInfo_ExtIEs;
struct S_TMSI_ExtIEs;
struct TAIBasedMDT_ExtIEs;
struct TAI_ExtIEs;
struct TAI_Broadcast_Item_ExtIEs;
struct TAI_Cancelled_Item_ExtIEs;
struct TABasedMDT_ExtIEs;
struct CompletedCellinTAI_Item_ExtIEs;
struct TargeteNB_ID_ExtIEs;
struct TargetRNC_ID_ExtIEs;
struct TargeteNB_ToSourceeNB_TransparentContainer_ExtIEs;
struct M1ThresholdEventA2_ExtIEs;
struct TraceActivation_ExtIEs;
struct Tunnel_Information_ExtIEs;
struct UEAggregate_MaximumBitrates_ExtIEs;
struct UE_S1AP_ID_pair_ExtIEs;
struct UE_associatedLogicalS1_ConnectionItemExtIEs;
struct UESecurityCapabilities_ExtIEs;
struct UserLocationInformation_ExtIEs;
struct X2TNLConfigurationInfo_ExtIEs;
struct ENBX2ExtTLA_ExtIEs;

/* ProtocolExtensionContainer */
typedef struct ProtocolExtensionContainer_5589P0 {
	A_SEQUENCE_OF(struct E_RABDataForwardingItem_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_5589P0_t;
typedef struct ProtocolExtensionContainer_5589P1 {
	A_SEQUENCE_OF(struct E_RABToBeSetupItemHOReq_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_5589P1_t;
typedef struct ProtocolExtensionContainer_5589P2 {
	A_SEQUENCE_OF(struct E_RABAdmittedItem_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_5589P2_t;
typedef struct ProtocolExtensionContainer_5589P3 {
	A_SEQUENCE_OF(struct E_RABFailedToSetupItemHOReqAckExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_5589P3_t;
typedef struct ProtocolExtensionContainer_5589P4 {
	A_SEQUENCE_OF(struct E_RABToBeSwitchedDLItem_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_5589P4_t;
typedef struct ProtocolExtensionContainer_5589P5 {
	A_SEQUENCE_OF(struct E_RABToBeSwitchedULItem_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_5589P5_t;
typedef struct ProtocolExtensionContainer_5589P6 {
	A_SEQUENCE_OF(struct E_RABToBeSetupItemBearerSUReqExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_5589P6_t;
typedef struct ProtocolExtensionContainer_5589P7 {
	A_SEQUENCE_OF(struct E_RABSetupItemBearerSUResExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_5589P7_t;
typedef struct ProtocolExtensionContainer_5589P8 {
	A_SEQUENCE_OF(struct E_RABToBeModifyItemBearerModReqExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_5589P8_t;
typedef struct ProtocolExtensionContainer_5589P9 {
	A_SEQUENCE_OF(struct E_RABModifyItemBearerModResExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_5589P9_t;
typedef struct ProtocolExtensionContainer_5589P10 {
	A_SEQUENCE_OF(struct E_RABReleaseItemBearerRelCompExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_5589P10_t;
typedef struct ProtocolExtensionContainer_5589P11 {
	A_SEQUENCE_OF(struct E_RABToBeSetupItemCtxtSUReqExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_5589P11_t;
typedef struct ProtocolExtensionContainer_5589P12 {
	A_SEQUENCE_OF(struct E_RABSetupItemCtxtSUResExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_5589P12_t;
typedef struct ProtocolExtensionContainer_5589P13 {
	A_SEQUENCE_OF(struct TAIItemExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_5589P13_t;
typedef struct ProtocolExtensionContainer_5589P14 {
	A_SEQUENCE_OF(struct E_RABToBeModifiedItemBearerModInd_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_5589P14_t;
typedef struct ProtocolExtensionContainer_5589P15 {
	A_SEQUENCE_OF(struct E_RABNotToBeModifiedItemBearerModInd_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_5589P15_t;
typedef struct ProtocolExtensionContainer_5589P16 {
	A_SEQUENCE_OF(struct E_RABModifyItemBearerModConfExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_5589P16_t;
typedef struct ProtocolExtensionContainer_5589P17 {
	A_SEQUENCE_OF(struct AllocationAndRetentionPriority_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_5589P17_t;
typedef struct ProtocolExtensionContainer_5589P18 {
	A_SEQUENCE_OF(struct Bearers_SubjectToStatusTransfer_ItemExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_5589P18_t;
typedef struct ProtocolExtensionContainer_5589P19 {
	A_SEQUENCE_OF(struct CancelledCellinEAI_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_5589P19_t;
typedef struct ProtocolExtensionContainer_5589P20 {
	A_SEQUENCE_OF(struct CancelledCellinTAI_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_5589P20_t;
typedef struct ProtocolExtensionContainer_5589P21 {
	A_SEQUENCE_OF(struct CellID_Broadcast_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_5589P21_t;
typedef struct ProtocolExtensionContainer_5589P22 {
	A_SEQUENCE_OF(struct CellID_Cancelled_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_5589P22_t;
typedef struct ProtocolExtensionContainer_5589P23 {
	A_SEQUENCE_OF(struct CellBasedMDT_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_5589P23_t;
typedef struct ProtocolExtensionContainer_5589P24 {
	A_SEQUENCE_OF(struct Cdma2000OneXSRVCCInfo_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_5589P24_t;
typedef struct ProtocolExtensionContainer_5589P25 {
	A_SEQUENCE_OF(struct CellType_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_5589P25_t;
typedef struct ProtocolExtensionContainer_5589P26 {
	A_SEQUENCE_OF(struct CGI_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_5589P26_t;
typedef struct ProtocolExtensionContainer_5589P27 {
	A_SEQUENCE_OF(struct CSG_IdList_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_5589P27_t;
typedef struct ProtocolExtensionContainer_5589P28 {
	A_SEQUENCE_OF(struct COUNTvalue_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_5589P28_t;
typedef struct ProtocolExtensionContainer_5589P29 {
	A_SEQUENCE_OF(struct COUNTValueExtended_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_5589P29_t;
typedef struct ProtocolExtensionContainer_5589P30 {
	A_SEQUENCE_OF(struct CriticalityDiagnostics_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_5589P30_t;
typedef struct ProtocolExtensionContainer_5589P31 {
	A_SEQUENCE_OF(struct CriticalityDiagnostics_IE_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_5589P31_t;
typedef struct ProtocolExtensionContainer_5589P32 {
	A_SEQUENCE_OF(struct EmergencyAreaID_Broadcast_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_5589P32_t;
typedef struct ProtocolExtensionContainer_5589P33 {
	A_SEQUENCE_OF(struct EmergencyAreaID_Cancelled_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_5589P33_t;
typedef struct ProtocolExtensionContainer_5589P34 {
	A_SEQUENCE_OF(struct CompletedCellinEAI_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_5589P34_t;
typedef struct ProtocolExtensionContainer_5589P35 {
	A_SEQUENCE_OF(struct GERAN_Cell_ID_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_5589P35_t;
typedef struct ProtocolExtensionContainer_5589P36 {
	A_SEQUENCE_OF(struct GlobalENB_ID_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_5589P36_t;
typedef struct ProtocolExtensionContainer_5589P37 {
	A_SEQUENCE_OF(struct ENB_StatusTransfer_TransparentContainer_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_5589P37_t;
typedef struct ProtocolExtensionContainer_5589P38 {
	A_SEQUENCE_OF(struct E_RABInformationListItem_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_5589P38_t;
typedef struct ProtocolExtensionContainer_5589P39 {
	A_SEQUENCE_OF(struct E_RABItem_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_5589P39_t;
typedef struct ProtocolExtensionContainer_5589P40 {
	A_SEQUENCE_OF(struct E_RABQoSParameters_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_5589P40_t;
typedef struct ProtocolExtensionContainer_5589P41 {
	A_SEQUENCE_OF(struct EUTRAN_CGI_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_5589P41_t;
typedef struct ProtocolExtensionContainer_5589P42 {
	A_SEQUENCE_OF(struct ExpectedUEBehaviour_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_5589P42_t;
typedef struct ProtocolExtensionContainer_5589P43 {
	A_SEQUENCE_OF(struct ExpectedUEActivityBehaviour_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_5589P43_t;
typedef struct ProtocolExtensionContainer_5589P44 {
	A_SEQUENCE_OF(struct ForbiddenTAs_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_5589P44_t;
typedef struct ProtocolExtensionContainer_5589P45 {
	A_SEQUENCE_OF(struct ForbiddenLAs_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_5589P45_t;
typedef struct ProtocolExtensionContainer_5589P46 {
	A_SEQUENCE_OF(struct GBR_QosInformation_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_5589P46_t;
typedef struct ProtocolExtensionContainer_5589P47 {
	A_SEQUENCE_OF(struct GUMMEI_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_5589P47_t;
typedef struct ProtocolExtensionContainer_5589P48 {
	A_SEQUENCE_OF(struct HandoverRestrictionList_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_5589P48_t;
typedef struct ProtocolExtensionContainer_5589P49 {
	A_SEQUENCE_OF(struct ImmediateMDT_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_5589P49_t;
typedef struct ProtocolExtensionContainer_5589P50 {
	A_SEQUENCE_OF(struct LAI_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_5589P50_t;
typedef struct ProtocolExtensionContainer_5589P51 {
	A_SEQUENCE_OF(struct LastVisitedEUTRANCellInformation_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_5589P51_t;
typedef struct ProtocolExtensionContainer_5589P52 {
	A_SEQUENCE_OF(struct ListeningSubframePattern_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_5589P52_t;
typedef struct ProtocolExtensionContainer_5589P53 {
	A_SEQUENCE_OF(struct LoggedMDT_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_5589P53_t;
typedef struct ProtocolExtensionContainer_5589P54 {
	A_SEQUENCE_OF(struct LoggedMBSFNMDT_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_5589P54_t;
typedef struct ProtocolExtensionContainer_5589P55 {
	A_SEQUENCE_OF(struct M3Configuration_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_5589P55_t;
typedef struct ProtocolExtensionContainer_5589P56 {
	A_SEQUENCE_OF(struct M4Configuration_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_5589P56_t;
typedef struct ProtocolExtensionContainer_5589P57 {
	A_SEQUENCE_OF(struct M5Configuration_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_5589P57_t;
typedef struct ProtocolExtensionContainer_5589P58 {
	A_SEQUENCE_OF(struct MDT_Configuration_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_5589P58_t;
typedef struct ProtocolExtensionContainer_5589P59 {
	A_SEQUENCE_OF(struct MBSFN_ResultToLogInfo_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_5589P59_t;
typedef struct ProtocolExtensionContainer_5589P60 {
	A_SEQUENCE_OF(struct MutingPatternInformation_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_5589P60_t;
typedef struct ProtocolExtensionContainer_5589P61 {
	A_SEQUENCE_OF(struct M1PeriodicReporting_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_5589P61_t;
typedef struct ProtocolExtensionContainer_5589P62 {
	A_SEQUENCE_OF(struct ProSeAuthorized_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_5589P62_t;
typedef struct ProtocolExtensionContainer_5589P63 {
	A_SEQUENCE_OF(struct RequestType_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_5589P63_t;
typedef struct ProtocolExtensionContainer_5589P64 {
	A_SEQUENCE_OF(struct RIMTransfer_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_5589P64_t;
typedef struct ProtocolExtensionContainer_5589P65 {
	A_SEQUENCE_OF(struct RLFReportInformation_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_5589P65_t;
typedef struct ProtocolExtensionContainer_5589P66 {
	A_SEQUENCE_OF(struct SecurityContext_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_5589P66_t;
typedef struct ProtocolExtensionContainer_5589P67 {
	A_SEQUENCE_OF(struct SONInformationReply_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_5589P67_t;
typedef struct ProtocolExtensionContainer_5589P68 {
	A_SEQUENCE_OF(struct SONConfigurationTransfer_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_5589P68_t;
typedef struct ProtocolExtensionContainer_5589P69 {
	A_SEQUENCE_OF(struct SynchronisationInformation_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_5589P69_t;
typedef struct ProtocolExtensionContainer_5589P70 {
	A_SEQUENCE_OF(struct SourceeNB_ID_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_5589P70_t;
typedef struct ProtocolExtensionContainer_5589P71 {
	A_SEQUENCE_OF(struct SourceeNB_ToTargeteNB_TransparentContainer_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_5589P71_t;
typedef struct ProtocolExtensionContainer_5589P72 {
	A_SEQUENCE_OF(struct ServedGUMMEIsItem_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_5589P72_t;
typedef struct ProtocolExtensionContainer_5589P73 {
	A_SEQUENCE_OF(struct SupportedTAs_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_5589P73_t;
typedef struct ProtocolExtensionContainer_5589P74 {
	A_SEQUENCE_OF(struct TimeSynchronisationInfo_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_5589P74_t;
typedef struct ProtocolExtensionContainer_5589P75 {
	A_SEQUENCE_OF(struct S_TMSI_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_5589P75_t;
typedef struct ProtocolExtensionContainer_5589P76 {
	A_SEQUENCE_OF(struct TAIBasedMDT_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_5589P76_t;
typedef struct ProtocolExtensionContainer_5589P77 {
	A_SEQUENCE_OF(struct TAI_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_5589P77_t;
typedef struct ProtocolExtensionContainer_5589P78 {
	A_SEQUENCE_OF(struct TAI_Broadcast_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_5589P78_t;
typedef struct ProtocolExtensionContainer_5589P79 {
	A_SEQUENCE_OF(struct TAI_Cancelled_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_5589P79_t;
typedef struct ProtocolExtensionContainer_5589P80 {
	A_SEQUENCE_OF(struct TABasedMDT_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_5589P80_t;
typedef struct ProtocolExtensionContainer_5589P81 {
	A_SEQUENCE_OF(struct CompletedCellinTAI_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_5589P81_t;
typedef struct ProtocolExtensionContainer_5589P82 {
	A_SEQUENCE_OF(struct TargeteNB_ID_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_5589P82_t;
typedef struct ProtocolExtensionContainer_5589P83 {
	A_SEQUENCE_OF(struct TargetRNC_ID_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_5589P83_t;
typedef struct ProtocolExtensionContainer_5589P84 {
	A_SEQUENCE_OF(struct TargeteNB_ToSourceeNB_TransparentContainer_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_5589P84_t;
typedef struct ProtocolExtensionContainer_5589P85 {
	A_SEQUENCE_OF(struct M1ThresholdEventA2_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_5589P85_t;
typedef struct ProtocolExtensionContainer_5589P86 {
	A_SEQUENCE_OF(struct TraceActivation_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_5589P86_t;
typedef struct ProtocolExtensionContainer_5589P87 {
	A_SEQUENCE_OF(struct Tunnel_Information_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_5589P87_t;
typedef struct ProtocolExtensionContainer_5589P88 {
	A_SEQUENCE_OF(struct UEAggregate_MaximumBitrates_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_5589P88_t;
typedef struct ProtocolExtensionContainer_5589P89 {
	A_SEQUENCE_OF(struct UE_S1AP_ID_pair_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_5589P89_t;
typedef struct ProtocolExtensionContainer_5589P90 {
	A_SEQUENCE_OF(struct UE_associatedLogicalS1_ConnectionItemExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_5589P90_t;
typedef struct ProtocolExtensionContainer_5589P91 {
	A_SEQUENCE_OF(struct UESecurityCapabilities_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_5589P91_t;
typedef struct ProtocolExtensionContainer_5589P92 {
	A_SEQUENCE_OF(struct UserLocationInformation_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_5589P92_t;
typedef struct ProtocolExtensionContainer_5589P93 {
	A_SEQUENCE_OF(struct X2TNLConfigurationInfo_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_5589P93_t;
typedef struct ProtocolExtensionContainer_5589P94 {
	A_SEQUENCE_OF(struct ENBX2ExtTLA_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_5589P94_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_5589P0;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_5589P0_specs_1;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_5589P0_1[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_5589P0_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_5589P1;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_5589P1_specs_3;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_5589P1_3[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_5589P1_constr_3;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_5589P2;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_5589P2_specs_5;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_5589P2_5[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_5589P2_constr_5;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_5589P3;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_5589P3_specs_7;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_5589P3_7[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_5589P3_constr_7;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_5589P4;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_5589P4_specs_9;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_5589P4_9[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_5589P4_constr_9;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_5589P5;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_5589P5_specs_11;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_5589P5_11[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_5589P5_constr_11;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_5589P6;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_5589P6_specs_13;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_5589P6_13[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_5589P6_constr_13;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_5589P7;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_5589P7_specs_15;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_5589P7_15[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_5589P7_constr_15;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_5589P8;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_5589P8_specs_17;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_5589P8_17[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_5589P8_constr_17;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_5589P9;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_5589P9_specs_19;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_5589P9_19[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_5589P9_constr_19;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_5589P10;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_5589P10_specs_21;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_5589P10_21[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_5589P10_constr_21;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_5589P11;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_5589P11_specs_23;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_5589P11_23[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_5589P11_constr_23;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_5589P12;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_5589P12_specs_25;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_5589P12_25[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_5589P12_constr_25;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_5589P13;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_5589P13_specs_27;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_5589P13_27[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_5589P13_constr_27;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_5589P14;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_5589P14_specs_29;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_5589P14_29[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_5589P14_constr_29;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_5589P15;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_5589P15_specs_31;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_5589P15_31[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_5589P15_constr_31;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_5589P16;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_5589P16_specs_33;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_5589P16_33[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_5589P16_constr_33;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_5589P17;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_5589P17_specs_35;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_5589P17_35[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_5589P17_constr_35;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_5589P18;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_5589P18_specs_37;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_5589P18_37[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_5589P18_constr_37;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_5589P19;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_5589P19_specs_39;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_5589P19_39[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_5589P19_constr_39;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_5589P20;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_5589P20_specs_41;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_5589P20_41[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_5589P20_constr_41;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_5589P21;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_5589P21_specs_43;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_5589P21_43[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_5589P21_constr_43;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_5589P22;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_5589P22_specs_45;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_5589P22_45[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_5589P22_constr_45;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_5589P23;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_5589P23_specs_47;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_5589P23_47[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_5589P23_constr_47;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_5589P24;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_5589P24_specs_49;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_5589P24_49[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_5589P24_constr_49;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_5589P25;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_5589P25_specs_51;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_5589P25_51[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_5589P25_constr_51;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_5589P26;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_5589P26_specs_53;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_5589P26_53[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_5589P26_constr_53;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_5589P27;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_5589P27_specs_55;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_5589P27_55[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_5589P27_constr_55;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_5589P28;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_5589P28_specs_57;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_5589P28_57[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_5589P28_constr_57;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_5589P29;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_5589P29_specs_59;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_5589P29_59[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_5589P29_constr_59;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_5589P30;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_5589P30_specs_61;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_5589P30_61[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_5589P30_constr_61;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_5589P31;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_5589P31_specs_63;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_5589P31_63[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_5589P31_constr_63;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_5589P32;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_5589P32_specs_65;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_5589P32_65[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_5589P32_constr_65;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_5589P33;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_5589P33_specs_67;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_5589P33_67[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_5589P33_constr_67;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_5589P34;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_5589P34_specs_69;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_5589P34_69[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_5589P34_constr_69;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_5589P35;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_5589P35_specs_71;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_5589P35_71[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_5589P35_constr_71;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_5589P36;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_5589P36_specs_73;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_5589P36_73[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_5589P36_constr_73;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_5589P37;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_5589P37_specs_75;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_5589P37_75[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_5589P37_constr_75;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_5589P38;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_5589P38_specs_77;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_5589P38_77[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_5589P38_constr_77;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_5589P39;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_5589P39_specs_79;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_5589P39_79[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_5589P39_constr_79;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_5589P40;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_5589P40_specs_81;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_5589P40_81[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_5589P40_constr_81;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_5589P41;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_5589P41_specs_83;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_5589P41_83[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_5589P41_constr_83;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_5589P42;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_5589P42_specs_85;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_5589P42_85[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_5589P42_constr_85;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_5589P43;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_5589P43_specs_87;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_5589P43_87[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_5589P43_constr_87;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_5589P44;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_5589P44_specs_89;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_5589P44_89[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_5589P44_constr_89;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_5589P45;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_5589P45_specs_91;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_5589P45_91[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_5589P45_constr_91;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_5589P46;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_5589P46_specs_93;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_5589P46_93[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_5589P46_constr_93;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_5589P47;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_5589P47_specs_95;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_5589P47_95[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_5589P47_constr_95;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_5589P48;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_5589P48_specs_97;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_5589P48_97[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_5589P48_constr_97;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_5589P49;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_5589P49_specs_99;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_5589P49_99[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_5589P49_constr_99;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_5589P50;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_5589P50_specs_101;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_5589P50_101[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_5589P50_constr_101;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_5589P51;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_5589P51_specs_103;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_5589P51_103[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_5589P51_constr_103;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_5589P52;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_5589P52_specs_105;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_5589P52_105[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_5589P52_constr_105;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_5589P53;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_5589P53_specs_107;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_5589P53_107[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_5589P53_constr_107;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_5589P54;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_5589P54_specs_109;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_5589P54_109[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_5589P54_constr_109;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_5589P55;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_5589P55_specs_111;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_5589P55_111[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_5589P55_constr_111;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_5589P56;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_5589P56_specs_113;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_5589P56_113[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_5589P56_constr_113;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_5589P57;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_5589P57_specs_115;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_5589P57_115[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_5589P57_constr_115;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_5589P58;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_5589P58_specs_117;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_5589P58_117[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_5589P58_constr_117;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_5589P59;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_5589P59_specs_119;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_5589P59_119[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_5589P59_constr_119;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_5589P60;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_5589P60_specs_121;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_5589P60_121[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_5589P60_constr_121;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_5589P61;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_5589P61_specs_123;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_5589P61_123[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_5589P61_constr_123;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_5589P62;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_5589P62_specs_125;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_5589P62_125[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_5589P62_constr_125;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_5589P63;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_5589P63_specs_127;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_5589P63_127[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_5589P63_constr_127;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_5589P64;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_5589P64_specs_129;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_5589P64_129[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_5589P64_constr_129;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_5589P65;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_5589P65_specs_131;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_5589P65_131[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_5589P65_constr_131;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_5589P66;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_5589P66_specs_133;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_5589P66_133[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_5589P66_constr_133;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_5589P67;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_5589P67_specs_135;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_5589P67_135[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_5589P67_constr_135;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_5589P68;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_5589P68_specs_137;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_5589P68_137[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_5589P68_constr_137;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_5589P69;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_5589P69_specs_139;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_5589P69_139[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_5589P69_constr_139;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_5589P70;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_5589P70_specs_141;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_5589P70_141[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_5589P70_constr_141;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_5589P71;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_5589P71_specs_143;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_5589P71_143[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_5589P71_constr_143;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_5589P72;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_5589P72_specs_145;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_5589P72_145[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_5589P72_constr_145;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_5589P73;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_5589P73_specs_147;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_5589P73_147[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_5589P73_constr_147;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_5589P74;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_5589P74_specs_149;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_5589P74_149[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_5589P74_constr_149;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_5589P75;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_5589P75_specs_151;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_5589P75_151[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_5589P75_constr_151;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_5589P76;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_5589P76_specs_153;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_5589P76_153[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_5589P76_constr_153;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_5589P77;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_5589P77_specs_155;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_5589P77_155[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_5589P77_constr_155;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_5589P78;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_5589P78_specs_157;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_5589P78_157[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_5589P78_constr_157;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_5589P79;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_5589P79_specs_159;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_5589P79_159[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_5589P79_constr_159;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_5589P80;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_5589P80_specs_161;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_5589P80_161[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_5589P80_constr_161;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_5589P81;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_5589P81_specs_163;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_5589P81_163[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_5589P81_constr_163;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_5589P82;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_5589P82_specs_165;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_5589P82_165[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_5589P82_constr_165;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_5589P83;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_5589P83_specs_167;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_5589P83_167[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_5589P83_constr_167;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_5589P84;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_5589P84_specs_169;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_5589P84_169[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_5589P84_constr_169;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_5589P85;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_5589P85_specs_171;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_5589P85_171[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_5589P85_constr_171;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_5589P86;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_5589P86_specs_173;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_5589P86_173[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_5589P86_constr_173;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_5589P87;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_5589P87_specs_175;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_5589P87_175[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_5589P87_constr_175;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_5589P88;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_5589P88_specs_177;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_5589P88_177[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_5589P88_constr_177;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_5589P89;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_5589P89_specs_179;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_5589P89_179[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_5589P89_constr_179;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_5589P90;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_5589P90_specs_181;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_5589P90_181[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_5589P90_constr_181;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_5589P91;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_5589P91_specs_183;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_5589P91_183[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_5589P91_constr_183;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_5589P92;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_5589P92_specs_185;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_5589P92_185[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_5589P92_constr_185;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_5589P93;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_5589P93_specs_187;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_5589P93_187[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_5589P93_constr_187;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_5589P94;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_5589P94_specs_189;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_5589P94_189[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_5589P94_constr_189;

#ifdef __cplusplus
}
#endif

#endif	/* _ProtocolExtensionContainer_H_ */
#include <asn_internal.h>
