/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-Containers"
 * 	found in "asn/s1ap_v12.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER -D include/`
 */

#ifndef	_ProtocolIE_Container_H_
#define	_ProtocolIE_Container_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct HandoverRequiredIEs;
struct HandoverCommandIEs;
struct HandoverPreparationFailureIEs;
struct HandoverRequestIEs;
struct HandoverRequestAcknowledgeIEs;
struct HandoverFailureIEs;
struct HandoverNotifyIEs;
struct PathSwitchRequestIEs;
struct PathSwitchRequestAcknowledgeIEs;
struct PathSwitchRequestFailureIEs;
struct HandoverCancelIEs;
struct HandoverCancelAcknowledgeIEs;
struct E_RABSetupRequestIEs;
struct E_RABSetupResponseIEs;
struct E_RABModifyRequestIEs;
struct E_RABModifyResponseIEs;
struct E_RABReleaseCommandIEs;
struct E_RABReleaseResponseIEs;
struct E_RABReleaseIndicationIEs;
struct InitialContextSetupRequestIEs;
struct InitialContextSetupResponseIEs;
struct InitialContextSetupFailureIEs;
struct PagingIEs;
struct UEContextReleaseRequest_IEs;
struct UEContextReleaseCommand_IEs;
struct UEContextReleaseComplete_IEs;
struct UEContextModificationRequestIEs;
struct UEContextModificationResponseIEs;
struct UEContextModificationFailureIEs;
struct UERadioCapabilityMatchRequestIEs;
struct UERadioCapabilityMatchResponseIEs;
struct DownlinkNASTransport_IEs;
struct InitialUEMessage_IEs;
struct UplinkNASTransport_IEs;
struct NASNonDeliveryIndication_IEs;
struct ResetIEs;
struct ResetAcknowledgeIEs;
struct ErrorIndicationIEs;
struct S1SetupRequestIEs;
struct S1SetupResponseIEs;
struct S1SetupFailureIEs;
struct ENBConfigurationUpdateIEs;
struct ENBConfigurationUpdateAcknowledgeIEs;
struct ENBConfigurationUpdateFailureIEs;
struct MMEConfigurationUpdateIEs;
struct MMEConfigurationUpdateAcknowledgeIEs;
struct MMEConfigurationUpdateFailureIEs;
struct DownlinkS1cdma2000tunnellingIEs;
struct UplinkS1cdma2000tunnellingIEs;
struct UECapabilityInfoIndicationIEs;
struct ENBStatusTransferIEs;
struct MMEStatusTransferIEs;
struct TraceStartIEs;
struct TraceFailureIndicationIEs;
struct DeactivateTraceIEs;
struct CellTrafficTraceIEs;
struct LocationReportingControlIEs;
struct LocationReportingFailureIndicationIEs;
struct LocationReportIEs;
struct OverloadStartIEs;
struct OverloadStopIEs;
struct WriteReplaceWarningRequestIEs;
struct WriteReplaceWarningResponseIEs;
struct ENBDirectInformationTransferIEs;
struct MMEDirectInformationTransferIEs;
struct ENBConfigurationTransferIEs;
struct MMEConfigurationTransferIEs;
struct KillRequestIEs;
struct KillResponseIEs;
struct PWSRestartIndicationIEs;
struct DownlinkUEAssociatedLPPaTransport_IEs;
struct UplinkUEAssociatedLPPaTransport_IEs;
struct DownlinkNonUEAssociatedLPPaTransport_IEs;
struct UplinkNonUEAssociatedLPPaTransport_IEs;
struct E_RABModificationIndicationIEs;
struct E_RABModificationConfirmIEs;

/* ProtocolIE-Container */
typedef struct ProtocolIE_Container_5538P0 {
	A_SEQUENCE_OF(struct HandoverRequiredIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5538P0_t;
typedef struct ProtocolIE_Container_5538P1 {
	A_SEQUENCE_OF(struct HandoverCommandIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5538P1_t;
typedef struct ProtocolIE_Container_5538P2 {
	A_SEQUENCE_OF(struct HandoverPreparationFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5538P2_t;
typedef struct ProtocolIE_Container_5538P3 {
	A_SEQUENCE_OF(struct HandoverRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5538P3_t;
typedef struct ProtocolIE_Container_5538P4 {
	A_SEQUENCE_OF(struct HandoverRequestAcknowledgeIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5538P4_t;
typedef struct ProtocolIE_Container_5538P5 {
	A_SEQUENCE_OF(struct HandoverFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5538P5_t;
typedef struct ProtocolIE_Container_5538P6 {
	A_SEQUENCE_OF(struct HandoverNotifyIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5538P6_t;
typedef struct ProtocolIE_Container_5538P7 {
	A_SEQUENCE_OF(struct PathSwitchRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5538P7_t;
typedef struct ProtocolIE_Container_5538P8 {
	A_SEQUENCE_OF(struct PathSwitchRequestAcknowledgeIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5538P8_t;
typedef struct ProtocolIE_Container_5538P9 {
	A_SEQUENCE_OF(struct PathSwitchRequestFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5538P9_t;
typedef struct ProtocolIE_Container_5538P10 {
	A_SEQUENCE_OF(struct HandoverCancelIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5538P10_t;
typedef struct ProtocolIE_Container_5538P11 {
	A_SEQUENCE_OF(struct HandoverCancelAcknowledgeIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5538P11_t;
typedef struct ProtocolIE_Container_5538P12 {
	A_SEQUENCE_OF(struct E_RABSetupRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5538P12_t;
typedef struct ProtocolIE_Container_5538P13 {
	A_SEQUENCE_OF(struct E_RABSetupResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5538P13_t;
typedef struct ProtocolIE_Container_5538P14 {
	A_SEQUENCE_OF(struct E_RABModifyRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5538P14_t;
typedef struct ProtocolIE_Container_5538P15 {
	A_SEQUENCE_OF(struct E_RABModifyResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5538P15_t;
typedef struct ProtocolIE_Container_5538P16 {
	A_SEQUENCE_OF(struct E_RABReleaseCommandIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5538P16_t;
typedef struct ProtocolIE_Container_5538P17 {
	A_SEQUENCE_OF(struct E_RABReleaseResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5538P17_t;
typedef struct ProtocolIE_Container_5538P18 {
	A_SEQUENCE_OF(struct E_RABReleaseIndicationIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5538P18_t;
typedef struct ProtocolIE_Container_5538P19 {
	A_SEQUENCE_OF(struct InitialContextSetupRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5538P19_t;
typedef struct ProtocolIE_Container_5538P20 {
	A_SEQUENCE_OF(struct InitialContextSetupResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5538P20_t;
typedef struct ProtocolIE_Container_5538P21 {
	A_SEQUENCE_OF(struct InitialContextSetupFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5538P21_t;
typedef struct ProtocolIE_Container_5538P22 {
	A_SEQUENCE_OF(struct PagingIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5538P22_t;
typedef struct ProtocolIE_Container_5538P23 {
	A_SEQUENCE_OF(struct UEContextReleaseRequest_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5538P23_t;
typedef struct ProtocolIE_Container_5538P24 {
	A_SEQUENCE_OF(struct UEContextReleaseCommand_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5538P24_t;
typedef struct ProtocolIE_Container_5538P25 {
	A_SEQUENCE_OF(struct UEContextReleaseComplete_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5538P25_t;
typedef struct ProtocolIE_Container_5538P26 {
	A_SEQUENCE_OF(struct UEContextModificationRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5538P26_t;
typedef struct ProtocolIE_Container_5538P27 {
	A_SEQUENCE_OF(struct UEContextModificationResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5538P27_t;
typedef struct ProtocolIE_Container_5538P28 {
	A_SEQUENCE_OF(struct UEContextModificationFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5538P28_t;
typedef struct ProtocolIE_Container_5538P29 {
	A_SEQUENCE_OF(struct UERadioCapabilityMatchRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5538P29_t;
typedef struct ProtocolIE_Container_5538P30 {
	A_SEQUENCE_OF(struct UERadioCapabilityMatchResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5538P30_t;
typedef struct ProtocolIE_Container_5538P31 {
	A_SEQUENCE_OF(struct DownlinkNASTransport_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5538P31_t;
typedef struct ProtocolIE_Container_5538P32 {
	A_SEQUENCE_OF(struct InitialUEMessage_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5538P32_t;
typedef struct ProtocolIE_Container_5538P33 {
	A_SEQUENCE_OF(struct UplinkNASTransport_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5538P33_t;
typedef struct ProtocolIE_Container_5538P34 {
	A_SEQUENCE_OF(struct NASNonDeliveryIndication_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5538P34_t;
typedef struct ProtocolIE_Container_5538P35 {
	A_SEQUENCE_OF(struct ResetIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5538P35_t;
typedef struct ProtocolIE_Container_5538P36 {
	A_SEQUENCE_OF(struct ResetAcknowledgeIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5538P36_t;
typedef struct ProtocolIE_Container_5538P37 {
	A_SEQUENCE_OF(struct ErrorIndicationIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5538P37_t;
typedef struct ProtocolIE_Container_5538P38 {
	A_SEQUENCE_OF(struct S1SetupRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5538P38_t;
typedef struct ProtocolIE_Container_5538P39 {
	A_SEQUENCE_OF(struct S1SetupResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5538P39_t;
typedef struct ProtocolIE_Container_5538P40 {
	A_SEQUENCE_OF(struct S1SetupFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5538P40_t;
typedef struct ProtocolIE_Container_5538P41 {
	A_SEQUENCE_OF(struct ENBConfigurationUpdateIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5538P41_t;
typedef struct ProtocolIE_Container_5538P42 {
	A_SEQUENCE_OF(struct ENBConfigurationUpdateAcknowledgeIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5538P42_t;
typedef struct ProtocolIE_Container_5538P43 {
	A_SEQUENCE_OF(struct ENBConfigurationUpdateFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5538P43_t;
typedef struct ProtocolIE_Container_5538P44 {
	A_SEQUENCE_OF(struct MMEConfigurationUpdateIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5538P44_t;
typedef struct ProtocolIE_Container_5538P45 {
	A_SEQUENCE_OF(struct MMEConfigurationUpdateAcknowledgeIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5538P45_t;
typedef struct ProtocolIE_Container_5538P46 {
	A_SEQUENCE_OF(struct MMEConfigurationUpdateFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5538P46_t;
typedef struct ProtocolIE_Container_5538P47 {
	A_SEQUENCE_OF(struct DownlinkS1cdma2000tunnellingIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5538P47_t;
typedef struct ProtocolIE_Container_5538P48 {
	A_SEQUENCE_OF(struct UplinkS1cdma2000tunnellingIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5538P48_t;
typedef struct ProtocolIE_Container_5538P49 {
	A_SEQUENCE_OF(struct UECapabilityInfoIndicationIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5538P49_t;
typedef struct ProtocolIE_Container_5538P50 {
	A_SEQUENCE_OF(struct ENBStatusTransferIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5538P50_t;
typedef struct ProtocolIE_Container_5538P51 {
	A_SEQUENCE_OF(struct MMEStatusTransferIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5538P51_t;
typedef struct ProtocolIE_Container_5538P52 {
	A_SEQUENCE_OF(struct TraceStartIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5538P52_t;
typedef struct ProtocolIE_Container_5538P53 {
	A_SEQUENCE_OF(struct TraceFailureIndicationIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5538P53_t;
typedef struct ProtocolIE_Container_5538P54 {
	A_SEQUENCE_OF(struct DeactivateTraceIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5538P54_t;
typedef struct ProtocolIE_Container_5538P55 {
	A_SEQUENCE_OF(struct CellTrafficTraceIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5538P55_t;
typedef struct ProtocolIE_Container_5538P56 {
	A_SEQUENCE_OF(struct LocationReportingControlIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5538P56_t;
typedef struct ProtocolIE_Container_5538P57 {
	A_SEQUENCE_OF(struct LocationReportingFailureIndicationIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5538P57_t;
typedef struct ProtocolIE_Container_5538P58 {
	A_SEQUENCE_OF(struct LocationReportIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5538P58_t;
typedef struct ProtocolIE_Container_5538P59 {
	A_SEQUENCE_OF(struct OverloadStartIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5538P59_t;
typedef struct ProtocolIE_Container_5538P60 {
	A_SEQUENCE_OF(struct OverloadStopIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5538P60_t;
typedef struct ProtocolIE_Container_5538P61 {
	A_SEQUENCE_OF(struct WriteReplaceWarningRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5538P61_t;
typedef struct ProtocolIE_Container_5538P62 {
	A_SEQUENCE_OF(struct WriteReplaceWarningResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5538P62_t;
typedef struct ProtocolIE_Container_5538P63 {
	A_SEQUENCE_OF(struct ENBDirectInformationTransferIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5538P63_t;
typedef struct ProtocolIE_Container_5538P64 {
	A_SEQUENCE_OF(struct MMEDirectInformationTransferIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5538P64_t;
typedef struct ProtocolIE_Container_5538P65 {
	A_SEQUENCE_OF(struct ENBConfigurationTransferIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5538P65_t;
typedef struct ProtocolIE_Container_5538P66 {
	A_SEQUENCE_OF(struct MMEConfigurationTransferIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5538P66_t;
typedef struct ProtocolIE_Container_5538P67 {
	A_SEQUENCE_OF(struct KillRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5538P67_t;
typedef struct ProtocolIE_Container_5538P68 {
	A_SEQUENCE_OF(struct KillResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5538P68_t;
typedef struct ProtocolIE_Container_5538P69 {
	A_SEQUENCE_OF(struct PWSRestartIndicationIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5538P69_t;
typedef struct ProtocolIE_Container_5538P70 {
	A_SEQUENCE_OF(struct DownlinkUEAssociatedLPPaTransport_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5538P70_t;
typedef struct ProtocolIE_Container_5538P71 {
	A_SEQUENCE_OF(struct UplinkUEAssociatedLPPaTransport_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5538P71_t;
typedef struct ProtocolIE_Container_5538P72 {
	A_SEQUENCE_OF(struct DownlinkNonUEAssociatedLPPaTransport_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5538P72_t;
typedef struct ProtocolIE_Container_5538P73 {
	A_SEQUENCE_OF(struct UplinkNonUEAssociatedLPPaTransport_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5538P73_t;
typedef struct ProtocolIE_Container_5538P74 {
	A_SEQUENCE_OF(struct E_RABModificationIndicationIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5538P74_t;
typedef struct ProtocolIE_Container_5538P75 {
	A_SEQUENCE_OF(struct E_RABModificationConfirmIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_5538P75_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5538P0;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5538P0_specs_1;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5538P0_1[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5538P0_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5538P1;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5538P1_specs_3;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5538P1_3[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5538P1_constr_3;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5538P2;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5538P2_specs_5;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5538P2_5[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5538P2_constr_5;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5538P3;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5538P3_specs_7;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5538P3_7[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5538P3_constr_7;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5538P4;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5538P4_specs_9;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5538P4_9[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5538P4_constr_9;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5538P5;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5538P5_specs_11;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5538P5_11[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5538P5_constr_11;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5538P6;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5538P6_specs_13;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5538P6_13[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5538P6_constr_13;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5538P7;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5538P7_specs_15;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5538P7_15[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5538P7_constr_15;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5538P8;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5538P8_specs_17;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5538P8_17[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5538P8_constr_17;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5538P9;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5538P9_specs_19;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5538P9_19[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5538P9_constr_19;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5538P10;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5538P10_specs_21;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5538P10_21[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5538P10_constr_21;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5538P11;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5538P11_specs_23;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5538P11_23[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5538P11_constr_23;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5538P12;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5538P12_specs_25;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5538P12_25[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5538P12_constr_25;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5538P13;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5538P13_specs_27;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5538P13_27[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5538P13_constr_27;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5538P14;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5538P14_specs_29;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5538P14_29[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5538P14_constr_29;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5538P15;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5538P15_specs_31;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5538P15_31[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5538P15_constr_31;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5538P16;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5538P16_specs_33;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5538P16_33[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5538P16_constr_33;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5538P17;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5538P17_specs_35;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5538P17_35[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5538P17_constr_35;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5538P18;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5538P18_specs_37;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5538P18_37[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5538P18_constr_37;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5538P19;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5538P19_specs_39;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5538P19_39[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5538P19_constr_39;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5538P20;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5538P20_specs_41;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5538P20_41[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5538P20_constr_41;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5538P21;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5538P21_specs_43;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5538P21_43[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5538P21_constr_43;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5538P22;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5538P22_specs_45;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5538P22_45[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5538P22_constr_45;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5538P23;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5538P23_specs_47;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5538P23_47[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5538P23_constr_47;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5538P24;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5538P24_specs_49;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5538P24_49[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5538P24_constr_49;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5538P25;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5538P25_specs_51;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5538P25_51[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5538P25_constr_51;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5538P26;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5538P26_specs_53;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5538P26_53[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5538P26_constr_53;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5538P27;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5538P27_specs_55;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5538P27_55[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5538P27_constr_55;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5538P28;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5538P28_specs_57;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5538P28_57[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5538P28_constr_57;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5538P29;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5538P29_specs_59;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5538P29_59[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5538P29_constr_59;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5538P30;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5538P30_specs_61;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5538P30_61[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5538P30_constr_61;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5538P31;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5538P31_specs_63;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5538P31_63[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5538P31_constr_63;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5538P32;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5538P32_specs_65;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5538P32_65[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5538P32_constr_65;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5538P33;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5538P33_specs_67;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5538P33_67[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5538P33_constr_67;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5538P34;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5538P34_specs_69;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5538P34_69[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5538P34_constr_69;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5538P35;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5538P35_specs_71;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5538P35_71[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5538P35_constr_71;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5538P36;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5538P36_specs_73;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5538P36_73[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5538P36_constr_73;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5538P37;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5538P37_specs_75;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5538P37_75[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5538P37_constr_75;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5538P38;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5538P38_specs_77;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5538P38_77[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5538P38_constr_77;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5538P39;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5538P39_specs_79;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5538P39_79[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5538P39_constr_79;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5538P40;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5538P40_specs_81;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5538P40_81[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5538P40_constr_81;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5538P41;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5538P41_specs_83;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5538P41_83[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5538P41_constr_83;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5538P42;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5538P42_specs_85;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5538P42_85[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5538P42_constr_85;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5538P43;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5538P43_specs_87;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5538P43_87[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5538P43_constr_87;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5538P44;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5538P44_specs_89;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5538P44_89[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5538P44_constr_89;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5538P45;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5538P45_specs_91;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5538P45_91[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5538P45_constr_91;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5538P46;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5538P46_specs_93;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5538P46_93[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5538P46_constr_93;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5538P47;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5538P47_specs_95;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5538P47_95[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5538P47_constr_95;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5538P48;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5538P48_specs_97;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5538P48_97[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5538P48_constr_97;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5538P49;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5538P49_specs_99;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5538P49_99[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5538P49_constr_99;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5538P50;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5538P50_specs_101;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5538P50_101[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5538P50_constr_101;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5538P51;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5538P51_specs_103;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5538P51_103[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5538P51_constr_103;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5538P52;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5538P52_specs_105;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5538P52_105[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5538P52_constr_105;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5538P53;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5538P53_specs_107;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5538P53_107[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5538P53_constr_107;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5538P54;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5538P54_specs_109;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5538P54_109[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5538P54_constr_109;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5538P55;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5538P55_specs_111;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5538P55_111[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5538P55_constr_111;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5538P56;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5538P56_specs_113;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5538P56_113[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5538P56_constr_113;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5538P57;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5538P57_specs_115;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5538P57_115[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5538P57_constr_115;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5538P58;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5538P58_specs_117;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5538P58_117[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5538P58_constr_117;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5538P59;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5538P59_specs_119;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5538P59_119[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5538P59_constr_119;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5538P60;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5538P60_specs_121;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5538P60_121[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5538P60_constr_121;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5538P61;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5538P61_specs_123;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5538P61_123[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5538P61_constr_123;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5538P62;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5538P62_specs_125;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5538P62_125[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5538P62_constr_125;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5538P63;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5538P63_specs_127;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5538P63_127[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5538P63_constr_127;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5538P64;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5538P64_specs_129;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5538P64_129[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5538P64_constr_129;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5538P65;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5538P65_specs_131;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5538P65_131[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5538P65_constr_131;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5538P66;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5538P66_specs_133;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5538P66_133[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5538P66_constr_133;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5538P67;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5538P67_specs_135;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5538P67_135[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5538P67_constr_135;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5538P68;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5538P68_specs_137;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5538P68_137[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5538P68_constr_137;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5538P69;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5538P69_specs_139;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5538P69_139[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5538P69_constr_139;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5538P70;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5538P70_specs_141;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5538P70_141[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5538P70_constr_141;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5538P71;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5538P71_specs_143;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5538P71_143[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5538P71_constr_143;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5538P72;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5538P72_specs_145;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5538P72_145[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5538P72_constr_145;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5538P73;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5538P73_specs_147;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5538P73_147[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5538P73_constr_147;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5538P74;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5538P74_specs_149;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5538P74_149[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5538P74_constr_149;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_5538P75;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_5538P75_specs_151;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_5538P75_151[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_5538P75_constr_151;

#ifdef __cplusplus
}
#endif

#endif	/* _ProtocolIE_Container_H_ */
#include <asn_internal.h>
