/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "asn/s1ap_v12.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER -D include/`
 */

#ifndef	_Routing_ID_H_
#define	_Routing_ID_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Routing-ID */
typedef long	 Routing_ID_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Routing_ID_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Routing_ID;
asn_struct_free_f Routing_ID_free;
asn_struct_print_f Routing_ID_print;
asn_constr_check_f Routing_ID_constraint;
per_type_decoder_f Routing_ID_decode_aper;
per_type_encoder_f Routing_ID_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _Routing_ID_H_ */
#include <asn_internal.h>
