/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "asn/s1ap_v12.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-XER -no-gen-OER -no-gen-UPER -no-gen-JER -D include/`
 */

#ifndef	_TBCD_STRING_H_
#define	_TBCD_STRING_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* TBCD-STRING */
typedef OCTET_STRING_t	 TBCD_STRING_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_TBCD_STRING_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_TBCD_STRING;
asn_struct_free_f TBCD_STRING_free;
asn_struct_print_f TBCD_STRING_print;
asn_constr_check_f TBCD_STRING_constraint;
per_type_decoder_f TBCD_STRING_decode_aper;
per_type_encoder_f TBCD_STRING_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _TBCD_STRING_H_ */
#include <asn_internal.h>
